// Code generated by Wire protocol buffer compiler, do not edit.
// Source: verifier.v1.TargetInfo in verifier.proto
package id.unum.protos.verifier.v1;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * Object to encapsulate Target information regarding customer's api versioning.
 */
public final class TargetInfo extends Message<TargetInfo, TargetInfo.Builder> {
  public static final ProtoAdapter<TargetInfo> ADAPTER = new ProtoAdapter_TargetInfo();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final String version;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final String url;

  public TargetInfo(String version, String url) {
    this(version, url, ByteString.EMPTY);
  }

  public TargetInfo(String version, String url, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (version == null) {
      throw new IllegalArgumentException("version == null");
    }
    this.version = version;
    if (url == null) {
      throw new IllegalArgumentException("url == null");
    }
    this.url = url;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.version = version;
    builder.url = url;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TargetInfo)) return false;
    TargetInfo o = (TargetInfo) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(version, o.version)
        && Internal.equals(url, o.url);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (version != null ? version.hashCode() : 0);
      result = result * 37 + (url != null ? url.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (version != null) builder.append(", version=").append(Internal.sanitize(version));
    if (url != null) builder.append(", url=").append(Internal.sanitize(url));
    return builder.replace(0, 2, "TargetInfo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<TargetInfo, Builder> {
    public String version;

    public String url;

    public Builder() {
      version = "";
      url = "";
    }

    public Builder version(String version) {
      this.version = version;
      return this;
    }

    public Builder url(String url) {
      this.url = url;
      return this;
    }

    @Override
    public TargetInfo build() {
      return new TargetInfo(version, url, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_TargetInfo extends ProtoAdapter<TargetInfo> {
    public ProtoAdapter_TargetInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, TargetInfo.class, "type.googleapis.com/verifier.v1.TargetInfo", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(TargetInfo value) {
      int result = 0;
      if (!Objects.equals(value.version, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.version);
      }
      if (!Objects.equals(value.url, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.url);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, TargetInfo value) throws IOException {
      if (!Objects.equals(value.version, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.version);
      if (!Objects.equals(value.url, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.url);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, TargetInfo value) throws IOException {
      writer.writeBytes(value.unknownFields());
      if (!Objects.equals(value.url, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.url);
      if (!Objects.equals(value.version, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.version);
    }

    @Override
    public TargetInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.version(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.url(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public TargetInfo redact(TargetInfo value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
