// Code generated by Wire protocol buffer compiler, do not edit.
// Source: verifier.v1.VerifierInfo in verifier.proto
package id.unum.protos.verifier.v1;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * Object to encapsulate basic verifier info
 */
public final class VerifierInfo extends Message<VerifierInfo, VerifierInfo.Builder> {
  public static final ProtoAdapter<VerifierInfo> ADAPTER = new ProtoAdapter_VerifierInfo();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final String did;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final String name;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final String url;

  public VerifierInfo(String did, String name, String url) {
    this(did, name, url, ByteString.EMPTY);
  }

  public VerifierInfo(String did, String name, String url, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (did == null) {
      throw new IllegalArgumentException("did == null");
    }
    this.did = did;
    if (name == null) {
      throw new IllegalArgumentException("name == null");
    }
    this.name = name;
    if (url == null) {
      throw new IllegalArgumentException("url == null");
    }
    this.url = url;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.did = did;
    builder.name = name;
    builder.url = url;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof VerifierInfo)) return false;
    VerifierInfo o = (VerifierInfo) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(did, o.did)
        && Internal.equals(name, o.name)
        && Internal.equals(url, o.url);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (did != null ? did.hashCode() : 0);
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (url != null ? url.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (did != null) builder.append(", did=").append(Internal.sanitize(did));
    if (name != null) builder.append(", name=").append(Internal.sanitize(name));
    if (url != null) builder.append(", url=").append(Internal.sanitize(url));
    return builder.replace(0, 2, "VerifierInfo{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<VerifierInfo, Builder> {
    public String did;

    public String name;

    public String url;

    public Builder() {
      did = "";
      name = "";
      url = "";
    }

    public Builder did(String did) {
      this.did = did;
      return this;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder url(String url) {
      this.url = url;
      return this;
    }

    @Override
    public VerifierInfo build() {
      return new VerifierInfo(did, name, url, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_VerifierInfo extends ProtoAdapter<VerifierInfo> {
    public ProtoAdapter_VerifierInfo() {
      super(FieldEncoding.LENGTH_DELIMITED, VerifierInfo.class, "type.googleapis.com/verifier.v1.VerifierInfo", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(VerifierInfo value) {
      int result = 0;
      if (!Objects.equals(value.did, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.did);
      }
      if (!Objects.equals(value.name, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.name);
      }
      if (!Objects.equals(value.url, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.url);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, VerifierInfo value) throws IOException {
      if (!Objects.equals(value.did, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.did);
      if (!Objects.equals(value.name, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name);
      if (!Objects.equals(value.url, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.url);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, VerifierInfo value) throws IOException {
      writer.writeBytes(value.unknownFields());
      if (!Objects.equals(value.url, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.url);
      if (!Objects.equals(value.name, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name);
      if (!Objects.equals(value.did, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.did);
    }

    @Override
    public VerifierInfo decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.did(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.name(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.url(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public VerifierInfo redact(VerifierInfo value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
