// Code generated by Wire protocol buffer compiler, do not edit.
// Source: credential.v1.CredentialStatus in credential.proto
package id.unum.protos.credential.v1;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Objects;
import okio.ByteString;

/**
 * Object to encapsulate Credential status information.
 */
public final class CredentialStatus extends Message<CredentialStatus, CredentialStatus.Builder> {
  public static final ProtoAdapter<CredentialStatus> ADAPTER = new ProtoAdapter_CredentialStatus();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final String id;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final String type;

  public CredentialStatus(String id, String type) {
    this(id, type, ByteString.EMPTY);
  }

  public CredentialStatus(String id, String type, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (id == null) {
      throw new IllegalArgumentException("id == null");
    }
    this.id = id;
    if (type == null) {
      throw new IllegalArgumentException("type == null");
    }
    this.type = type;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.type = type;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CredentialStatus)) return false;
    CredentialStatus o = (CredentialStatus) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(id, o.id)
        && Internal.equals(type, o.type);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (type != null ? type.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) builder.append(", id=").append(Internal.sanitize(id));
    if (type != null) builder.append(", type=").append(Internal.sanitize(type));
    return builder.replace(0, 2, "CredentialStatus{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CredentialStatus, Builder> {
    public String id;

    public String type;

    public Builder() {
      id = "";
      type = "";
    }

    public Builder id(String id) {
      this.id = id;
      return this;
    }

    public Builder type(String type) {
      this.type = type;
      return this;
    }

    @Override
    public CredentialStatus build() {
      return new CredentialStatus(id, type, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CredentialStatus extends ProtoAdapter<CredentialStatus> {
    public ProtoAdapter_CredentialStatus() {
      super(FieldEncoding.LENGTH_DELIMITED, CredentialStatus.class, "type.googleapis.com/credential.v1.CredentialStatus", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(CredentialStatus value) {
      int result = 0;
      if (!Objects.equals(value.id, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id);
      }
      if (!Objects.equals(value.type, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.type);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, CredentialStatus value) throws IOException {
      if (!Objects.equals(value.id, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id);
      if (!Objects.equals(value.type, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.type);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, CredentialStatus value) throws IOException {
      writer.writeBytes(value.unknownFields());
      if (!Objects.equals(value.type, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.type);
      if (!Objects.equals(value.id, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id);
    }

    @Override
    public CredentialStatus decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.type(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public CredentialStatus redact(CredentialStatus value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
