// Code generated by Wire protocol buffer compiler, do not edit.
// Source: issuer.v1.Issuer in issuer.proto
package id.unum.protos.issuer.v1;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.time.Instant;
import java.util.Objects;
import okio.ByteString;

/**
 * Object to encapsulate an Issuer entity
 */
public final class Issuer extends Message<Issuer, Issuer.Builder> {
  public static final ProtoAdapter<Issuer> ADAPTER = new ProtoAdapter_Issuer();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final String uuid;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY,
      jsonName = "customerUuid"
  )
  public final String customer_uuid;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final String name;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final String did;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
      label = WireField.Label.OMIT_IDENTITY,
      jsonName = "createdAt"
  )
  public final Instant created_at;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
      label = WireField.Label.OMIT_IDENTITY,
      jsonName = "updatedAt"
  )
  public final Instant updated_at;

  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL",
      label = WireField.Label.OMIT_IDENTITY,
      jsonName = "isAuthorized"
  )
  public final boolean is_authorized;

  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY,
      jsonName = "apiKey"
  )
  public final String api_key;

  public Issuer(String uuid, String customer_uuid, String name, String did, Instant created_at,
      Instant updated_at, boolean is_authorized, String api_key) {
    this(uuid, customer_uuid, name, did, created_at, updated_at, is_authorized, api_key, ByteString.EMPTY);
  }

  public Issuer(String uuid, String customer_uuid, String name, String did, Instant created_at,
      Instant updated_at, boolean is_authorized, String api_key, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    if (uuid == null) {
      throw new IllegalArgumentException("uuid == null");
    }
    this.uuid = uuid;
    if (customer_uuid == null) {
      throw new IllegalArgumentException("customer_uuid == null");
    }
    this.customer_uuid = customer_uuid;
    if (name == null) {
      throw new IllegalArgumentException("name == null");
    }
    this.name = name;
    if (did == null) {
      throw new IllegalArgumentException("did == null");
    }
    this.did = did;
    this.created_at = created_at;
    this.updated_at = updated_at;
    this.is_authorized = is_authorized;
    if (api_key == null) {
      throw new IllegalArgumentException("api_key == null");
    }
    this.api_key = api_key;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.uuid = uuid;
    builder.customer_uuid = customer_uuid;
    builder.name = name;
    builder.did = did;
    builder.created_at = created_at;
    builder.updated_at = updated_at;
    builder.is_authorized = is_authorized;
    builder.api_key = api_key;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Issuer)) return false;
    Issuer o = (Issuer) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(uuid, o.uuid)
        && Internal.equals(customer_uuid, o.customer_uuid)
        && Internal.equals(name, o.name)
        && Internal.equals(did, o.did)
        && Internal.equals(created_at, o.created_at)
        && Internal.equals(updated_at, o.updated_at)
        && Internal.equals(is_authorized, o.is_authorized)
        && Internal.equals(api_key, o.api_key);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (uuid != null ? uuid.hashCode() : 0);
      result = result * 37 + (customer_uuid != null ? customer_uuid.hashCode() : 0);
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (did != null ? did.hashCode() : 0);
      result = result * 37 + (created_at != null ? created_at.hashCode() : 0);
      result = result * 37 + (updated_at != null ? updated_at.hashCode() : 0);
      result = result * 37 + Boolean.hashCode(is_authorized);
      result = result * 37 + (api_key != null ? api_key.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (uuid != null) builder.append(", uuid=").append(Internal.sanitize(uuid));
    if (customer_uuid != null) builder.append(", customer_uuid=").append(Internal.sanitize(customer_uuid));
    if (name != null) builder.append(", name=").append(Internal.sanitize(name));
    if (did != null) builder.append(", did=").append(Internal.sanitize(did));
    if (created_at != null) builder.append(", created_at=").append(created_at);
    if (updated_at != null) builder.append(", updated_at=").append(updated_at);
    builder.append(", is_authorized=").append(is_authorized);
    if (api_key != null) builder.append(", api_key=").append(Internal.sanitize(api_key));
    return builder.replace(0, 2, "Issuer{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Issuer, Builder> {
    public String uuid;

    public String customer_uuid;

    public String name;

    public String did;

    public Instant created_at;

    public Instant updated_at;

    public boolean is_authorized;

    public String api_key;

    public Builder() {
      uuid = "";
      customer_uuid = "";
      name = "";
      did = "";
      is_authorized = false;
      api_key = "";
    }

    public Builder uuid(String uuid) {
      this.uuid = uuid;
      return this;
    }

    public Builder customer_uuid(String customer_uuid) {
      this.customer_uuid = customer_uuid;
      return this;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder did(String did) {
      this.did = did;
      return this;
    }

    public Builder created_at(Instant created_at) {
      this.created_at = created_at;
      return this;
    }

    public Builder updated_at(Instant updated_at) {
      this.updated_at = updated_at;
      return this;
    }

    public Builder is_authorized(boolean is_authorized) {
      this.is_authorized = is_authorized;
      return this;
    }

    public Builder api_key(String api_key) {
      this.api_key = api_key;
      return this;
    }

    @Override
    public Issuer build() {
      return new Issuer(uuid, customer_uuid, name, did, created_at, updated_at, is_authorized, api_key, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Issuer extends ProtoAdapter<Issuer> {
    public ProtoAdapter_Issuer() {
      super(FieldEncoding.LENGTH_DELIMITED, Issuer.class, "type.googleapis.com/issuer.v1.Issuer", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(Issuer value) {
      int result = 0;
      if (!Objects.equals(value.uuid, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.uuid);
      }
      if (!Objects.equals(value.customer_uuid, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.customer_uuid);
      }
      if (!Objects.equals(value.name, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.name);
      }
      if (!Objects.equals(value.did, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(4, value.did);
      }
      if (!Objects.equals(value.created_at, null)) {
        result += ProtoAdapter.INSTANT.encodedSizeWithTag(5, value.created_at);
      }
      if (!Objects.equals(value.updated_at, null)) {
        result += ProtoAdapter.INSTANT.encodedSizeWithTag(6, value.updated_at);
      }
      if (!Objects.equals(value.is_authorized, false)) {
        result += ProtoAdapter.BOOL.encodedSizeWithTag(7, value.is_authorized);
      }
      if (!Objects.equals(value.api_key, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(8, value.api_key);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, Issuer value) throws IOException {
      if (!Objects.equals(value.uuid, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.uuid);
      if (!Objects.equals(value.customer_uuid, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.customer_uuid);
      if (!Objects.equals(value.name, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.name);
      if (!Objects.equals(value.did, "")) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.did);
      if (!Objects.equals(value.created_at, null)) ProtoAdapter.INSTANT.encodeWithTag(writer, 5, value.created_at);
      if (!Objects.equals(value.updated_at, null)) ProtoAdapter.INSTANT.encodeWithTag(writer, 6, value.updated_at);
      if (!Objects.equals(value.is_authorized, false)) ProtoAdapter.BOOL.encodeWithTag(writer, 7, value.is_authorized);
      if (!Objects.equals(value.api_key, "")) ProtoAdapter.STRING.encodeWithTag(writer, 8, value.api_key);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, Issuer value) throws IOException {
      writer.writeBytes(value.unknownFields());
      if (!Objects.equals(value.api_key, "")) ProtoAdapter.STRING.encodeWithTag(writer, 8, value.api_key);
      if (!Objects.equals(value.is_authorized, false)) ProtoAdapter.BOOL.encodeWithTag(writer, 7, value.is_authorized);
      if (!Objects.equals(value.updated_at, null)) ProtoAdapter.INSTANT.encodeWithTag(writer, 6, value.updated_at);
      if (!Objects.equals(value.created_at, null)) ProtoAdapter.INSTANT.encodeWithTag(writer, 5, value.created_at);
      if (!Objects.equals(value.did, "")) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.did);
      if (!Objects.equals(value.name, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.name);
      if (!Objects.equals(value.customer_uuid, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.customer_uuid);
      if (!Objects.equals(value.uuid, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.uuid);
    }

    @Override
    public Issuer decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.uuid(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.customer_uuid(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.name(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.did(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.created_at(ProtoAdapter.INSTANT.decode(reader)); break;
          case 6: builder.updated_at(ProtoAdapter.INSTANT.decode(reader)); break;
          case 7: builder.is_authorized(ProtoAdapter.BOOL.decode(reader)); break;
          case 8: builder.api_key(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public Issuer redact(Issuer value) {
      Builder builder = value.newBuilder();
      if (builder.created_at != null) builder.created_at = ProtoAdapter.INSTANT.redact(builder.created_at);
      if (builder.updated_at != null) builder.updated_at = ProtoAdapter.INSTANT.redact(builder.updated_at);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
