// Code generated by Wire protocol buffer compiler, do not edit.
// Source: presentationRequestEnriched.v1.PresentationRequestEnriched in presentationRequestEnriched.proto
package id.unum.protos.presentationRequestEnriched.v1;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import id.unum.protos.holderApp.v1.HolderAppInfo;
import id.unum.protos.presentationRequest.v1.PresentationRequest;
import id.unum.protos.verifier.v1.VerifierInfo;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.Map;
import java.util.Objects;
import okio.ByteString;

/**
 * Encapsulates presentation request attributes as they are retuned from Unum ID saas.
 */
public final class PresentationRequestEnriched extends Message<PresentationRequestEnriched, PresentationRequestEnriched.Builder> {
  public static final ProtoAdapter<PresentationRequestEnriched> ADAPTER = new ProtoAdapter_PresentationRequestEnriched();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "id.unum.protos.presentationRequest.v1.PresentationRequest#ADAPTER",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final PresentationRequest presentationRequest;

  @WireField(
      tag = 2,
      adapter = "id.unum.protos.verifier.v1.VerifierInfo#ADAPTER",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final VerifierInfo verifierInfo;

  /**
   * a map of issuer metadata keyed on the issuer's did
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRUCT_MAP",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final Map<String, ?> issuers;

  @WireField(
      tag = 4,
      adapter = "id.unum.protos.holderApp.v1.HolderAppInfo#ADAPTER",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final HolderAppInfo holderApp;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final String deeplink;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY
  )
  public final String qrCode;

  public PresentationRequestEnriched(PresentationRequest presentationRequest,
      VerifierInfo verifierInfo, Map<String, ?> issuers, HolderAppInfo holderApp, String deeplink,
      String qrCode) {
    this(presentationRequest, verifierInfo, issuers, holderApp, deeplink, qrCode, ByteString.EMPTY);
  }

  public PresentationRequestEnriched(PresentationRequest presentationRequest,
      VerifierInfo verifierInfo, Map<String, ?> issuers, HolderAppInfo holderApp, String deeplink,
      String qrCode, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.presentationRequest = presentationRequest;
    this.verifierInfo = verifierInfo;
    this.issuers = Internal.immutableCopyOfStruct("issuers", issuers);
    this.holderApp = holderApp;
    if (deeplink == null) {
      throw new IllegalArgumentException("deeplink == null");
    }
    this.deeplink = deeplink;
    if (qrCode == null) {
      throw new IllegalArgumentException("qrCode == null");
    }
    this.qrCode = qrCode;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.presentationRequest = presentationRequest;
    builder.verifierInfo = verifierInfo;
    builder.issuers = issuers;
    builder.holderApp = holderApp;
    builder.deeplink = deeplink;
    builder.qrCode = qrCode;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PresentationRequestEnriched)) return false;
    PresentationRequestEnriched o = (PresentationRequestEnriched) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(presentationRequest, o.presentationRequest)
        && Internal.equals(verifierInfo, o.verifierInfo)
        && Internal.equals(issuers, o.issuers)
        && Internal.equals(holderApp, o.holderApp)
        && Internal.equals(deeplink, o.deeplink)
        && Internal.equals(qrCode, o.qrCode);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (presentationRequest != null ? presentationRequest.hashCode() : 0);
      result = result * 37 + (verifierInfo != null ? verifierInfo.hashCode() : 0);
      result = result * 37 + (issuers != null ? issuers.hashCode() : 0);
      result = result * 37 + (holderApp != null ? holderApp.hashCode() : 0);
      result = result * 37 + (deeplink != null ? deeplink.hashCode() : 0);
      result = result * 37 + (qrCode != null ? qrCode.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (presentationRequest != null) builder.append(", presentationRequest=").append(presentationRequest);
    if (verifierInfo != null) builder.append(", verifierInfo=").append(verifierInfo);
    if (issuers != null) builder.append(", issuers=").append(issuers);
    if (holderApp != null) builder.append(", holderApp=").append(holderApp);
    if (deeplink != null) builder.append(", deeplink=").append(Internal.sanitize(deeplink));
    if (qrCode != null) builder.append(", qrCode=").append(Internal.sanitize(qrCode));
    return builder.replace(0, 2, "PresentationRequestEnriched{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PresentationRequestEnriched, Builder> {
    public PresentationRequest presentationRequest;

    public VerifierInfo verifierInfo;

    public Map<String, ?> issuers;

    public HolderAppInfo holderApp;

    public String deeplink;

    public String qrCode;

    public Builder() {
      deeplink = "";
      qrCode = "";
    }

    public Builder presentationRequest(PresentationRequest presentationRequest) {
      this.presentationRequest = presentationRequest;
      return this;
    }

    public Builder verifierInfo(VerifierInfo verifierInfo) {
      this.verifierInfo = verifierInfo;
      return this;
    }

    /**
     * a map of issuer metadata keyed on the issuer's did
     */
    public Builder issuers(Map<String, ?> issuers) {
      this.issuers = issuers;
      return this;
    }

    public Builder holderApp(HolderAppInfo holderApp) {
      this.holderApp = holderApp;
      return this;
    }

    public Builder deeplink(String deeplink) {
      this.deeplink = deeplink;
      return this;
    }

    public Builder qrCode(String qrCode) {
      this.qrCode = qrCode;
      return this;
    }

    @Override
    public PresentationRequestEnriched build() {
      return new PresentationRequestEnriched(presentationRequest, verifierInfo, issuers, holderApp, deeplink, qrCode, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PresentationRequestEnriched extends ProtoAdapter<PresentationRequestEnriched> {
    public ProtoAdapter_PresentationRequestEnriched() {
      super(FieldEncoding.LENGTH_DELIMITED, PresentationRequestEnriched.class, "type.googleapis.com/presentationRequestEnriched.v1.PresentationRequestEnriched", Syntax.PROTO_3, null);
    }

    @Override
    public int encodedSize(PresentationRequestEnriched value) {
      int result = 0;
      if (!Objects.equals(value.presentationRequest, null)) {
        result += PresentationRequest.ADAPTER.encodedSizeWithTag(1, value.presentationRequest);
      }
      if (!Objects.equals(value.verifierInfo, null)) {
        result += VerifierInfo.ADAPTER.encodedSizeWithTag(2, value.verifierInfo);
      }
      if (!Objects.equals(value.issuers, null)) {
        result += ProtoAdapter.STRUCT_MAP.encodedSizeWithTag(3, value.issuers);
      }
      if (!Objects.equals(value.holderApp, null)) {
        result += HolderAppInfo.ADAPTER.encodedSizeWithTag(4, value.holderApp);
      }
      if (!Objects.equals(value.deeplink, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(5, value.deeplink);
      }
      if (!Objects.equals(value.qrCode, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(6, value.qrCode);
      }
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, PresentationRequestEnriched value) throws IOException {
      if (!Objects.equals(value.presentationRequest, null)) PresentationRequest.ADAPTER.encodeWithTag(writer, 1, value.presentationRequest);
      if (!Objects.equals(value.verifierInfo, null)) VerifierInfo.ADAPTER.encodeWithTag(writer, 2, value.verifierInfo);
      if (!Objects.equals(value.issuers, null)) ProtoAdapter.STRUCT_MAP.encodeWithTag(writer, 3, value.issuers);
      if (!Objects.equals(value.holderApp, null)) HolderAppInfo.ADAPTER.encodeWithTag(writer, 4, value.holderApp);
      if (!Objects.equals(value.deeplink, "")) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.deeplink);
      if (!Objects.equals(value.qrCode, "")) ProtoAdapter.STRING.encodeWithTag(writer, 6, value.qrCode);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, PresentationRequestEnriched value) throws
        IOException {
      writer.writeBytes(value.unknownFields());
      if (!Objects.equals(value.qrCode, "")) ProtoAdapter.STRING.encodeWithTag(writer, 6, value.qrCode);
      if (!Objects.equals(value.deeplink, "")) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.deeplink);
      if (!Objects.equals(value.holderApp, null)) HolderAppInfo.ADAPTER.encodeWithTag(writer, 4, value.holderApp);
      if (!Objects.equals(value.issuers, null)) ProtoAdapter.STRUCT_MAP.encodeWithTag(writer, 3, value.issuers);
      if (!Objects.equals(value.verifierInfo, null)) VerifierInfo.ADAPTER.encodeWithTag(writer, 2, value.verifierInfo);
      if (!Objects.equals(value.presentationRequest, null)) PresentationRequest.ADAPTER.encodeWithTag(writer, 1, value.presentationRequest);
    }

    @Override
    public PresentationRequestEnriched decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.presentationRequest(PresentationRequest.ADAPTER.decode(reader)); break;
          case 2: builder.verifierInfo(VerifierInfo.ADAPTER.decode(reader)); break;
          case 3: builder.issuers(ProtoAdapter.STRUCT_MAP.decode(reader)); break;
          case 4: builder.holderApp(HolderAppInfo.ADAPTER.decode(reader)); break;
          case 5: builder.deeplink(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.qrCode(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public PresentationRequestEnriched redact(PresentationRequestEnriched value) {
      Builder builder = value.newBuilder();
      if (builder.presentationRequest != null) builder.presentationRequest = PresentationRequest.ADAPTER.redact(builder.presentationRequest);
      if (builder.verifierInfo != null) builder.verifierInfo = VerifierInfo.ADAPTER.redact(builder.verifierInfo);
      if (builder.issuers != null) builder.issuers = ProtoAdapter.STRUCT_MAP.redact(builder.issuers);
      if (builder.holderApp != null) builder.holderApp = HolderAppInfo.ADAPTER.redact(builder.holderApp);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
