// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: presentation.proto

package presentation.v1;

public final class PresentationProto {
  private PresentationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_presentation_v1_UnsignedPresentation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_presentation_v1_UnsignedPresentation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_presentation_v1_Presentation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_presentation_v1_Presentation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_presentation_v1_UnsignedPresentationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_presentation_v1_UnsignedPresentationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_presentation_v1_PresentationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_presentation_v1_PresentationRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022presentation.proto\022\017presentation.v1\032\020c" +
      "redential.proto\032\013proof.proto\032\037google/pro" +
      "tobuf/timestamp.proto\"\245\001\n\024UnsignedPresen" +
      "tation\022\017\n\007context\030\001 \003(\t\022\014\n\004type\030\002 \003(\t\022\037\n" +
      "\027presentation_request_id\030\003 \001(\t\022\023\n\013verifi" +
      "erDid\030\004 \001(\t\0228\n\025verifiable_credential\030\005 \003" +
      "(\0132\031.credential.v1.Credential\"\276\001\n\014Presen" +
      "tation\022\017\n\007context\030\001 \003(\t\022\014\n\004type\030\002 \003(\t\022\037\n" +
      "\027presentation_request_id\030\003 \001(\t\022\023\n\013verifi" +
      "erDid\030\004 \001(\t\0228\n\025verifiable_credential\030\005 \003" +
      "(\0132\031.credential.v1.Credential\022\037\n\005proof\030\006" +
      " \001(\0132\020.crypto.v1.Proof\"\324\002\n\033UnsignedPrese" +
      "ntationRequest\022=\n\023credential_requests\030\001 " +
      "\003(\0132 .credential.v1.CredentialRequest\022\027\n" +
      "\017holder_app_uuid\030\002 \001(\t\022\020\n\010verifier\030\003 \001(\t" +
      "\022.\n\ncreated_at\030\004 \001(\0132\032.google.protobuf.T" +
      "imestamp\022.\n\nupdated_at\030\005 \001(\0132\032.google.pr" +
      "otobuf.Timestamp\022.\n\nexpires_at\030\006 \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\022\020\n\010metadata\030\007 \001" +
      "(\t\022\014\n\004uuid\030\010 \001(\t\022\n\n\002id\030\t \001(\t\022\017\n\007version\030" +
      "\n \001(\t\"\355\002\n\023PresentationRequest\022=\n\023credent" +
      "ial_requests\030\001 \003(\0132 .credential.v1.Crede" +
      "ntialRequest\022\027\n\017holder_app_uuid\030\002 \001(\t\022\020\n" +
      "\010verifier\030\003 \001(\t\022.\n\ncreated_at\030\004 \001(\0132\032.go" +
      "ogle.protobuf.Timestamp\022.\n\nupdated_at\030\005 " +
      "\001(\0132\032.google.protobuf.Timestamp\022.\n\nexpir" +
      "es_at\030\006 \001(\0132\032.google.protobuf.Timestamp\022" +
      "\020\n\010metadata\030\007 \001(\t\022\014\n\004uuid\030\010 \001(\t\022\037\n\005proof" +
      "\030\t \001(\0132\020.crypto.v1.Proof\022\n\n\002id\030\n \001(\t\022\017\n\007" +
      "version\030\013 \001(\tB\025B\021PresentationProtoP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          credential.v1.CredentialProto.getDescriptor(),
          crypto.v1.ProofProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_presentation_v1_UnsignedPresentation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_presentation_v1_UnsignedPresentation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_presentation_v1_UnsignedPresentation_descriptor,
        new java.lang.String[] { "Context", "Type", "PresentationRequestId", "VerifierDid", "VerifiableCredential", });
    internal_static_presentation_v1_Presentation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_presentation_v1_Presentation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_presentation_v1_Presentation_descriptor,
        new java.lang.String[] { "Context", "Type", "PresentationRequestId", "VerifierDid", "VerifiableCredential", "Proof", });
    internal_static_presentation_v1_UnsignedPresentationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_presentation_v1_UnsignedPresentationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_presentation_v1_UnsignedPresentationRequest_descriptor,
        new java.lang.String[] { "CredentialRequests", "HolderAppUuid", "Verifier", "CreatedAt", "UpdatedAt", "ExpiresAt", "Metadata", "Uuid", "Id", "Version", });
    internal_static_presentation_v1_PresentationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_presentation_v1_PresentationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_presentation_v1_PresentationRequest_descriptor,
        new java.lang.String[] { "CredentialRequests", "HolderAppUuid", "Verifier", "CreatedAt", "UpdatedAt", "ExpiresAt", "Metadata", "Uuid", "Proof", "Id", "Version", });
    credential.v1.CredentialProto.getDescriptor();
    crypto.v1.ProofProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
