// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: presentation.proto

package presentation.v1;

/**
 * <pre>
 **
 * Encapsulates addition attributes to the unsigned presentation entity to create a Presentation entity.
 * Tightly coupled with UnsignedPresentation.
 * </pre>
 *
 * Protobuf type {@code presentation.v1.Presentation}
 */
public  final class Presentation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:presentation.v1.Presentation)
    PresentationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Presentation.newBuilder() to construct.
  private Presentation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Presentation() {
    context_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    type_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    presentationRequestId_ = "";
    verifierDid_ = "";
    verifiableCredential_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Presentation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              context_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            context_.add(s);
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              type_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            type_.add(s);
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            presentationRequestId_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            verifierDid_ = s;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              verifiableCredential_ = new java.util.ArrayList<credential.v1.Credential>();
              mutable_bitField0_ |= 0x00000010;
            }
            verifiableCredential_.add(
                input.readMessage(credential.v1.Credential.parser(), extensionRegistry));
            break;
          }
          case 50: {
            crypto.v1.Proof.Builder subBuilder = null;
            if (proof_ != null) {
              subBuilder = proof_.toBuilder();
            }
            proof_ = input.readMessage(crypto.v1.Proof.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(proof_);
              proof_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        context_ = context_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        type_ = type_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        verifiableCredential_ = java.util.Collections.unmodifiableList(verifiableCredential_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return presentation.v1.PresentationProto.internal_static_presentation_v1_Presentation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return presentation.v1.PresentationProto.internal_static_presentation_v1_Presentation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            presentation.v1.Presentation.class, presentation.v1.Presentation.Builder.class);
  }

  private int bitField0_;
  public static final int CONTEXT_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList context_;
  /**
   * <code>repeated string context = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getContextList() {
    return context_;
  }
  /**
   * <code>repeated string context = 1;</code>
   */
  public int getContextCount() {
    return context_.size();
  }
  /**
   * <code>repeated string context = 1;</code>
   */
  public java.lang.String getContext(int index) {
    return context_.get(index);
  }
  /**
   * <code>repeated string context = 1;</code>
   */
  public com.google.protobuf.ByteString
      getContextBytes(int index) {
    return context_.getByteString(index);
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList type_;
  /**
   * <code>repeated string type = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getTypeList() {
    return type_;
  }
  /**
   * <code>repeated string type = 2;</code>
   */
  public int getTypeCount() {
    return type_.size();
  }
  /**
   * <code>repeated string type = 2;</code>
   */
  public java.lang.String getType(int index) {
    return type_.get(index);
  }
  /**
   * <code>repeated string type = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes(int index) {
    return type_.getByteString(index);
  }

  public static final int PRESENTATION_REQUEST_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object presentationRequestId_;
  /**
   * <code>string presentation_request_id = 3;</code>
   */
  public java.lang.String getPresentationRequestId() {
    java.lang.Object ref = presentationRequestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      presentationRequestId_ = s;
      return s;
    }
  }
  /**
   * <code>string presentation_request_id = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPresentationRequestIdBytes() {
    java.lang.Object ref = presentationRequestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      presentationRequestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERIFIERDID_FIELD_NUMBER = 4;
  private volatile java.lang.Object verifierDid_;
  /**
   * <code>string verifierDid = 4;</code>
   */
  public java.lang.String getVerifierDid() {
    java.lang.Object ref = verifierDid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      verifierDid_ = s;
      return s;
    }
  }
  /**
   * <code>string verifierDid = 4;</code>
   */
  public com.google.protobuf.ByteString
      getVerifierDidBytes() {
    java.lang.Object ref = verifierDid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      verifierDid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERIFIABLE_CREDENTIAL_FIELD_NUMBER = 5;
  private java.util.List<credential.v1.Credential> verifiableCredential_;
  /**
   * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
   */
  public java.util.List<credential.v1.Credential> getVerifiableCredentialList() {
    return verifiableCredential_;
  }
  /**
   * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
   */
  public java.util.List<? extends credential.v1.CredentialOrBuilder> 
      getVerifiableCredentialOrBuilderList() {
    return verifiableCredential_;
  }
  /**
   * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
   */
  public int getVerifiableCredentialCount() {
    return verifiableCredential_.size();
  }
  /**
   * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
   */
  public credential.v1.Credential getVerifiableCredential(int index) {
    return verifiableCredential_.get(index);
  }
  /**
   * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
   */
  public credential.v1.CredentialOrBuilder getVerifiableCredentialOrBuilder(
      int index) {
    return verifiableCredential_.get(index);
  }

  public static final int PROOF_FIELD_NUMBER = 6;
  private crypto.v1.Proof proof_;
  /**
   * <code>.crypto.v1.Proof proof = 6;</code>
   */
  public boolean hasProof() {
    return proof_ != null;
  }
  /**
   * <code>.crypto.v1.Proof proof = 6;</code>
   */
  public crypto.v1.Proof getProof() {
    return proof_ == null ? crypto.v1.Proof.getDefaultInstance() : proof_;
  }
  /**
   * <code>.crypto.v1.Proof proof = 6;</code>
   */
  public crypto.v1.ProofOrBuilder getProofOrBuilder() {
    return getProof();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < context_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, context_.getRaw(i));
    }
    for (int i = 0; i < type_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_.getRaw(i));
    }
    if (!getPresentationRequestIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, presentationRequestId_);
    }
    if (!getVerifierDidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, verifierDid_);
    }
    for (int i = 0; i < verifiableCredential_.size(); i++) {
      output.writeMessage(5, verifiableCredential_.get(i));
    }
    if (proof_ != null) {
      output.writeMessage(6, getProof());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < context_.size(); i++) {
        dataSize += computeStringSizeNoTag(context_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getContextList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < type_.size(); i++) {
        dataSize += computeStringSizeNoTag(type_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTypeList().size();
    }
    if (!getPresentationRequestIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, presentationRequestId_);
    }
    if (!getVerifierDidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, verifierDid_);
    }
    for (int i = 0; i < verifiableCredential_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, verifiableCredential_.get(i));
    }
    if (proof_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getProof());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof presentation.v1.Presentation)) {
      return super.equals(obj);
    }
    presentation.v1.Presentation other = (presentation.v1.Presentation) obj;

    boolean result = true;
    result = result && getContextList()
        .equals(other.getContextList());
    result = result && getTypeList()
        .equals(other.getTypeList());
    result = result && getPresentationRequestId()
        .equals(other.getPresentationRequestId());
    result = result && getVerifierDid()
        .equals(other.getVerifierDid());
    result = result && getVerifiableCredentialList()
        .equals(other.getVerifiableCredentialList());
    result = result && (hasProof() == other.hasProof());
    if (hasProof()) {
      result = result && getProof()
          .equals(other.getProof());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getContextCount() > 0) {
      hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getContextList().hashCode();
    }
    if (getTypeCount() > 0) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTypeList().hashCode();
    }
    hash = (37 * hash) + PRESENTATION_REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPresentationRequestId().hashCode();
    hash = (37 * hash) + VERIFIERDID_FIELD_NUMBER;
    hash = (53 * hash) + getVerifierDid().hashCode();
    if (getVerifiableCredentialCount() > 0) {
      hash = (37 * hash) + VERIFIABLE_CREDENTIAL_FIELD_NUMBER;
      hash = (53 * hash) + getVerifiableCredentialList().hashCode();
    }
    if (hasProof()) {
      hash = (37 * hash) + PROOF_FIELD_NUMBER;
      hash = (53 * hash) + getProof().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static presentation.v1.Presentation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static presentation.v1.Presentation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static presentation.v1.Presentation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static presentation.v1.Presentation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static presentation.v1.Presentation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static presentation.v1.Presentation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static presentation.v1.Presentation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static presentation.v1.Presentation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static presentation.v1.Presentation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static presentation.v1.Presentation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static presentation.v1.Presentation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static presentation.v1.Presentation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(presentation.v1.Presentation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * Encapsulates addition attributes to the unsigned presentation entity to create a Presentation entity.
   * Tightly coupled with UnsignedPresentation.
   * </pre>
   *
   * Protobuf type {@code presentation.v1.Presentation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:presentation.v1.Presentation)
      presentation.v1.PresentationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return presentation.v1.PresentationProto.internal_static_presentation_v1_Presentation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return presentation.v1.PresentationProto.internal_static_presentation_v1_Presentation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              presentation.v1.Presentation.class, presentation.v1.Presentation.Builder.class);
    }

    // Construct using presentation.v1.Presentation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVerifiableCredentialFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      context_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      presentationRequestId_ = "";

      verifierDid_ = "";

      if (verifiableCredentialBuilder_ == null) {
        verifiableCredential_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        verifiableCredentialBuilder_.clear();
      }
      if (proofBuilder_ == null) {
        proof_ = null;
      } else {
        proof_ = null;
        proofBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return presentation.v1.PresentationProto.internal_static_presentation_v1_Presentation_descriptor;
    }

    @java.lang.Override
    public presentation.v1.Presentation getDefaultInstanceForType() {
      return presentation.v1.Presentation.getDefaultInstance();
    }

    @java.lang.Override
    public presentation.v1.Presentation build() {
      presentation.v1.Presentation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public presentation.v1.Presentation buildPartial() {
      presentation.v1.Presentation result = new presentation.v1.Presentation(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        context_ = context_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.context_ = context_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        type_ = type_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.type_ = type_;
      result.presentationRequestId_ = presentationRequestId_;
      result.verifierDid_ = verifierDid_;
      if (verifiableCredentialBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          verifiableCredential_ = java.util.Collections.unmodifiableList(verifiableCredential_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.verifiableCredential_ = verifiableCredential_;
      } else {
        result.verifiableCredential_ = verifiableCredentialBuilder_.build();
      }
      if (proofBuilder_ == null) {
        result.proof_ = proof_;
      } else {
        result.proof_ = proofBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof presentation.v1.Presentation) {
        return mergeFrom((presentation.v1.Presentation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(presentation.v1.Presentation other) {
      if (other == presentation.v1.Presentation.getDefaultInstance()) return this;
      if (!other.context_.isEmpty()) {
        if (context_.isEmpty()) {
          context_ = other.context_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureContextIsMutable();
          context_.addAll(other.context_);
        }
        onChanged();
      }
      if (!other.type_.isEmpty()) {
        if (type_.isEmpty()) {
          type_ = other.type_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureTypeIsMutable();
          type_.addAll(other.type_);
        }
        onChanged();
      }
      if (!other.getPresentationRequestId().isEmpty()) {
        presentationRequestId_ = other.presentationRequestId_;
        onChanged();
      }
      if (!other.getVerifierDid().isEmpty()) {
        verifierDid_ = other.verifierDid_;
        onChanged();
      }
      if (verifiableCredentialBuilder_ == null) {
        if (!other.verifiableCredential_.isEmpty()) {
          if (verifiableCredential_.isEmpty()) {
            verifiableCredential_ = other.verifiableCredential_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureVerifiableCredentialIsMutable();
            verifiableCredential_.addAll(other.verifiableCredential_);
          }
          onChanged();
        }
      } else {
        if (!other.verifiableCredential_.isEmpty()) {
          if (verifiableCredentialBuilder_.isEmpty()) {
            verifiableCredentialBuilder_.dispose();
            verifiableCredentialBuilder_ = null;
            verifiableCredential_ = other.verifiableCredential_;
            bitField0_ = (bitField0_ & ~0x00000010);
            verifiableCredentialBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVerifiableCredentialFieldBuilder() : null;
          } else {
            verifiableCredentialBuilder_.addAllMessages(other.verifiableCredential_);
          }
        }
      }
      if (other.hasProof()) {
        mergeProof(other.getProof());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      presentation.v1.Presentation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (presentation.v1.Presentation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList context_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureContextIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        context_ = new com.google.protobuf.LazyStringArrayList(context_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getContextList() {
      return context_.getUnmodifiableView();
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public int getContextCount() {
      return context_.size();
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public java.lang.String getContext(int index) {
      return context_.get(index);
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContextBytes(int index) {
      return context_.getByteString(index);
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public Builder setContext(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureContextIsMutable();
      context_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public Builder addContext(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureContextIsMutable();
      context_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public Builder addAllContext(
        java.lang.Iterable<java.lang.String> values) {
      ensureContextIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, context_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public Builder clearContext() {
      context_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public Builder addContextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureContextIsMutable();
      context_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList type_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTypeIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        type_ = new com.google.protobuf.LazyStringArrayList(type_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string type = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTypeList() {
      return type_.getUnmodifiableView();
    }
    /**
     * <code>repeated string type = 2;</code>
     */
    public int getTypeCount() {
      return type_.size();
    }
    /**
     * <code>repeated string type = 2;</code>
     */
    public java.lang.String getType(int index) {
      return type_.get(index);
    }
    /**
     * <code>repeated string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes(int index) {
      return type_.getByteString(index);
    }
    /**
     * <code>repeated string type = 2;</code>
     */
    public Builder setType(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTypeIsMutable();
      type_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type = 2;</code>
     */
    public Builder addType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTypeIsMutable();
      type_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type = 2;</code>
     */
    public Builder addAllType(
        java.lang.Iterable<java.lang.String> values) {
      ensureTypeIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, type_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type = 2;</code>
     */
    public Builder clearType() {
      type_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type = 2;</code>
     */
    public Builder addTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTypeIsMutable();
      type_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object presentationRequestId_ = "";
    /**
     * <code>string presentation_request_id = 3;</code>
     */
    public java.lang.String getPresentationRequestId() {
      java.lang.Object ref = presentationRequestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        presentationRequestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string presentation_request_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPresentationRequestIdBytes() {
      java.lang.Object ref = presentationRequestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        presentationRequestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string presentation_request_id = 3;</code>
     */
    public Builder setPresentationRequestId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      presentationRequestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string presentation_request_id = 3;</code>
     */
    public Builder clearPresentationRequestId() {
      
      presentationRequestId_ = getDefaultInstance().getPresentationRequestId();
      onChanged();
      return this;
    }
    /**
     * <code>string presentation_request_id = 3;</code>
     */
    public Builder setPresentationRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      presentationRequestId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object verifierDid_ = "";
    /**
     * <code>string verifierDid = 4;</code>
     */
    public java.lang.String getVerifierDid() {
      java.lang.Object ref = verifierDid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        verifierDid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string verifierDid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getVerifierDidBytes() {
      java.lang.Object ref = verifierDid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verifierDid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string verifierDid = 4;</code>
     */
    public Builder setVerifierDid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      verifierDid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string verifierDid = 4;</code>
     */
    public Builder clearVerifierDid() {
      
      verifierDid_ = getDefaultInstance().getVerifierDid();
      onChanged();
      return this;
    }
    /**
     * <code>string verifierDid = 4;</code>
     */
    public Builder setVerifierDidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      verifierDid_ = value;
      onChanged();
      return this;
    }

    private java.util.List<credential.v1.Credential> verifiableCredential_ =
      java.util.Collections.emptyList();
    private void ensureVerifiableCredentialIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        verifiableCredential_ = new java.util.ArrayList<credential.v1.Credential>(verifiableCredential_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        credential.v1.Credential, credential.v1.Credential.Builder, credential.v1.CredentialOrBuilder> verifiableCredentialBuilder_;

    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public java.util.List<credential.v1.Credential> getVerifiableCredentialList() {
      if (verifiableCredentialBuilder_ == null) {
        return java.util.Collections.unmodifiableList(verifiableCredential_);
      } else {
        return verifiableCredentialBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public int getVerifiableCredentialCount() {
      if (verifiableCredentialBuilder_ == null) {
        return verifiableCredential_.size();
      } else {
        return verifiableCredentialBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public credential.v1.Credential getVerifiableCredential(int index) {
      if (verifiableCredentialBuilder_ == null) {
        return verifiableCredential_.get(index);
      } else {
        return verifiableCredentialBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public Builder setVerifiableCredential(
        int index, credential.v1.Credential value) {
      if (verifiableCredentialBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVerifiableCredentialIsMutable();
        verifiableCredential_.set(index, value);
        onChanged();
      } else {
        verifiableCredentialBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public Builder setVerifiableCredential(
        int index, credential.v1.Credential.Builder builderForValue) {
      if (verifiableCredentialBuilder_ == null) {
        ensureVerifiableCredentialIsMutable();
        verifiableCredential_.set(index, builderForValue.build());
        onChanged();
      } else {
        verifiableCredentialBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public Builder addVerifiableCredential(credential.v1.Credential value) {
      if (verifiableCredentialBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVerifiableCredentialIsMutable();
        verifiableCredential_.add(value);
        onChanged();
      } else {
        verifiableCredentialBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public Builder addVerifiableCredential(
        int index, credential.v1.Credential value) {
      if (verifiableCredentialBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVerifiableCredentialIsMutable();
        verifiableCredential_.add(index, value);
        onChanged();
      } else {
        verifiableCredentialBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public Builder addVerifiableCredential(
        credential.v1.Credential.Builder builderForValue) {
      if (verifiableCredentialBuilder_ == null) {
        ensureVerifiableCredentialIsMutable();
        verifiableCredential_.add(builderForValue.build());
        onChanged();
      } else {
        verifiableCredentialBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public Builder addVerifiableCredential(
        int index, credential.v1.Credential.Builder builderForValue) {
      if (verifiableCredentialBuilder_ == null) {
        ensureVerifiableCredentialIsMutable();
        verifiableCredential_.add(index, builderForValue.build());
        onChanged();
      } else {
        verifiableCredentialBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public Builder addAllVerifiableCredential(
        java.lang.Iterable<? extends credential.v1.Credential> values) {
      if (verifiableCredentialBuilder_ == null) {
        ensureVerifiableCredentialIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, verifiableCredential_);
        onChanged();
      } else {
        verifiableCredentialBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public Builder clearVerifiableCredential() {
      if (verifiableCredentialBuilder_ == null) {
        verifiableCredential_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        verifiableCredentialBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public Builder removeVerifiableCredential(int index) {
      if (verifiableCredentialBuilder_ == null) {
        ensureVerifiableCredentialIsMutable();
        verifiableCredential_.remove(index);
        onChanged();
      } else {
        verifiableCredentialBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public credential.v1.Credential.Builder getVerifiableCredentialBuilder(
        int index) {
      return getVerifiableCredentialFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public credential.v1.CredentialOrBuilder getVerifiableCredentialOrBuilder(
        int index) {
      if (verifiableCredentialBuilder_ == null) {
        return verifiableCredential_.get(index);  } else {
        return verifiableCredentialBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public java.util.List<? extends credential.v1.CredentialOrBuilder> 
         getVerifiableCredentialOrBuilderList() {
      if (verifiableCredentialBuilder_ != null) {
        return verifiableCredentialBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(verifiableCredential_);
      }
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public credential.v1.Credential.Builder addVerifiableCredentialBuilder() {
      return getVerifiableCredentialFieldBuilder().addBuilder(
          credential.v1.Credential.getDefaultInstance());
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public credential.v1.Credential.Builder addVerifiableCredentialBuilder(
        int index) {
      return getVerifiableCredentialFieldBuilder().addBuilder(
          index, credential.v1.Credential.getDefaultInstance());
    }
    /**
     * <code>repeated .credential.v1.Credential verifiable_credential = 5;</code>
     */
    public java.util.List<credential.v1.Credential.Builder> 
         getVerifiableCredentialBuilderList() {
      return getVerifiableCredentialFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        credential.v1.Credential, credential.v1.Credential.Builder, credential.v1.CredentialOrBuilder> 
        getVerifiableCredentialFieldBuilder() {
      if (verifiableCredentialBuilder_ == null) {
        verifiableCredentialBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            credential.v1.Credential, credential.v1.Credential.Builder, credential.v1.CredentialOrBuilder>(
                verifiableCredential_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        verifiableCredential_ = null;
      }
      return verifiableCredentialBuilder_;
    }

    private crypto.v1.Proof proof_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        crypto.v1.Proof, crypto.v1.Proof.Builder, crypto.v1.ProofOrBuilder> proofBuilder_;
    /**
     * <code>.crypto.v1.Proof proof = 6;</code>
     */
    public boolean hasProof() {
      return proofBuilder_ != null || proof_ != null;
    }
    /**
     * <code>.crypto.v1.Proof proof = 6;</code>
     */
    public crypto.v1.Proof getProof() {
      if (proofBuilder_ == null) {
        return proof_ == null ? crypto.v1.Proof.getDefaultInstance() : proof_;
      } else {
        return proofBuilder_.getMessage();
      }
    }
    /**
     * <code>.crypto.v1.Proof proof = 6;</code>
     */
    public Builder setProof(crypto.v1.Proof value) {
      if (proofBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        proof_ = value;
        onChanged();
      } else {
        proofBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.crypto.v1.Proof proof = 6;</code>
     */
    public Builder setProof(
        crypto.v1.Proof.Builder builderForValue) {
      if (proofBuilder_ == null) {
        proof_ = builderForValue.build();
        onChanged();
      } else {
        proofBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.crypto.v1.Proof proof = 6;</code>
     */
    public Builder mergeProof(crypto.v1.Proof value) {
      if (proofBuilder_ == null) {
        if (proof_ != null) {
          proof_ =
            crypto.v1.Proof.newBuilder(proof_).mergeFrom(value).buildPartial();
        } else {
          proof_ = value;
        }
        onChanged();
      } else {
        proofBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.crypto.v1.Proof proof = 6;</code>
     */
    public Builder clearProof() {
      if (proofBuilder_ == null) {
        proof_ = null;
        onChanged();
      } else {
        proof_ = null;
        proofBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.crypto.v1.Proof proof = 6;</code>
     */
    public crypto.v1.Proof.Builder getProofBuilder() {
      
      onChanged();
      return getProofFieldBuilder().getBuilder();
    }
    /**
     * <code>.crypto.v1.Proof proof = 6;</code>
     */
    public crypto.v1.ProofOrBuilder getProofOrBuilder() {
      if (proofBuilder_ != null) {
        return proofBuilder_.getMessageOrBuilder();
      } else {
        return proof_ == null ?
            crypto.v1.Proof.getDefaultInstance() : proof_;
      }
    }
    /**
     * <code>.crypto.v1.Proof proof = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        crypto.v1.Proof, crypto.v1.Proof.Builder, crypto.v1.ProofOrBuilder> 
        getProofFieldBuilder() {
      if (proofBuilder_ == null) {
        proofBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            crypto.v1.Proof, crypto.v1.Proof.Builder, crypto.v1.ProofOrBuilder>(
                getProof(),
                getParentForChildren(),
                isClean());
        proof_ = null;
      }
      return proofBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:presentation.v1.Presentation)
  }

  // @@protoc_insertion_point(class_scope:presentation.v1.Presentation)
  private static final presentation.v1.Presentation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new presentation.v1.Presentation();
  }

  public static presentation.v1.Presentation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Presentation>
      PARSER = new com.google.protobuf.AbstractParser<Presentation>() {
    @java.lang.Override
    public Presentation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Presentation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Presentation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Presentation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public presentation.v1.Presentation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

