// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: presentation.proto

package presentation.v1;

/**
 * <pre>
 **
 * Encapsulates request attributes for the purposes of requesting presentation of credentials.
 * </pre>
 *
 * Protobuf type {@code presentation.v1.UnsignedPresentationRequest}
 */
public  final class UnsignedPresentationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:presentation.v1.UnsignedPresentationRequest)
    UnsignedPresentationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UnsignedPresentationRequest.newBuilder() to construct.
  private UnsignedPresentationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UnsignedPresentationRequest() {
    credentialRequests_ = java.util.Collections.emptyList();
    holderAppUuid_ = "";
    verifier_ = "";
    metadata_ = "";
    uuid_ = "";
    id_ = "";
    version_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UnsignedPresentationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              credentialRequests_ = new java.util.ArrayList<credential.v1.CredentialRequest>();
              mutable_bitField0_ |= 0x00000001;
            }
            credentialRequests_.add(
                input.readMessage(credential.v1.CredentialRequest.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            holderAppUuid_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            verifier_ = s;
            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (createdAt_ != null) {
              subBuilder = createdAt_.toBuilder();
            }
            createdAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createdAt_);
              createdAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (updatedAt_ != null) {
              subBuilder = updatedAt_.toBuilder();
            }
            updatedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(updatedAt_);
              updatedAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (expiresAt_ != null) {
              subBuilder = expiresAt_.toBuilder();
            }
            expiresAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(expiresAt_);
              expiresAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            metadata_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            uuid_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        credentialRequests_ = java.util.Collections.unmodifiableList(credentialRequests_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return presentation.v1.PresentationProto.internal_static_presentation_v1_UnsignedPresentationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return presentation.v1.PresentationProto.internal_static_presentation_v1_UnsignedPresentationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            presentation.v1.UnsignedPresentationRequest.class, presentation.v1.UnsignedPresentationRequest.Builder.class);
  }

  private int bitField0_;
  public static final int CREDENTIAL_REQUESTS_FIELD_NUMBER = 1;
  private java.util.List<credential.v1.CredentialRequest> credentialRequests_;
  /**
   * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
   */
  public java.util.List<credential.v1.CredentialRequest> getCredentialRequestsList() {
    return credentialRequests_;
  }
  /**
   * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
   */
  public java.util.List<? extends credential.v1.CredentialRequestOrBuilder> 
      getCredentialRequestsOrBuilderList() {
    return credentialRequests_;
  }
  /**
   * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
   */
  public int getCredentialRequestsCount() {
    return credentialRequests_.size();
  }
  /**
   * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
   */
  public credential.v1.CredentialRequest getCredentialRequests(int index) {
    return credentialRequests_.get(index);
  }
  /**
   * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
   */
  public credential.v1.CredentialRequestOrBuilder getCredentialRequestsOrBuilder(
      int index) {
    return credentialRequests_.get(index);
  }

  public static final int HOLDER_APP_UUID_FIELD_NUMBER = 2;
  private volatile java.lang.Object holderAppUuid_;
  /**
   * <code>string holder_app_uuid = 2;</code>
   */
  public java.lang.String getHolderAppUuid() {
    java.lang.Object ref = holderAppUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      holderAppUuid_ = s;
      return s;
    }
  }
  /**
   * <code>string holder_app_uuid = 2;</code>
   */
  public com.google.protobuf.ByteString
      getHolderAppUuidBytes() {
    java.lang.Object ref = holderAppUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      holderAppUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERIFIER_FIELD_NUMBER = 3;
  private volatile java.lang.Object verifier_;
  /**
   * <code>string verifier = 3;</code>
   */
  public java.lang.String getVerifier() {
    java.lang.Object ref = verifier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      verifier_ = s;
      return s;
    }
  }
  /**
   * <code>string verifier = 3;</code>
   */
  public com.google.protobuf.ByteString
      getVerifierBytes() {
    java.lang.Object ref = verifier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      verifier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp created_at = 4;</code>
   */
  public boolean hasCreatedAt() {
    return createdAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 4;</code>
   */
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 4;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return getCreatedAt();
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp updatedAt_;
  /**
   * <code>.google.protobuf.Timestamp updated_at = 5;</code>
   */
  public boolean hasUpdatedAt() {
    return updatedAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 5;</code>
   */
  public com.google.protobuf.Timestamp getUpdatedAt() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 5;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
    return getUpdatedAt();
  }

  public static final int EXPIRES_AT_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp expiresAt_;
  /**
   * <code>.google.protobuf.Timestamp expires_at = 6;</code>
   */
  public boolean hasExpiresAt() {
    return expiresAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp expires_at = 6;</code>
   */
  public com.google.protobuf.Timestamp getExpiresAt() {
    return expiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp expires_at = 6;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getExpiresAtOrBuilder() {
    return getExpiresAt();
  }

  public static final int METADATA_FIELD_NUMBER = 7;
  private volatile java.lang.Object metadata_;
  /**
   * <pre>
   * a string representation of an ambiguous object. Note: the Any type does not work because still needs a scheme (but can be assigned dymanically) &amp; Struct does not work becuase not determinsitcally serialzied across langauges
   * </pre>
   *
   * <code>string metadata = 7;</code>
   */
  public java.lang.String getMetadata() {
    java.lang.Object ref = metadata_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      metadata_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * a string representation of an ambiguous object. Note: the Any type does not work because still needs a scheme (but can be assigned dymanically) &amp; Struct does not work becuase not determinsitcally serialzied across langauges
   * </pre>
   *
   * <code>string metadata = 7;</code>
   */
  public com.google.protobuf.ByteString
      getMetadataBytes() {
    java.lang.Object ref = metadata_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metadata_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UUID_FIELD_NUMBER = 8;
  private volatile java.lang.Object uuid_;
  /**
   * <code>string uuid = 8;</code>
   */
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <code>string uuid = 8;</code>
   */
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 9;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * an indentifier for related presetnation requests across versions
   * </pre>
   *
   * <code>string id = 9;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * an indentifier for related presetnation requests across versions
   * </pre>
   *
   * <code>string id = 9;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 10;
  private volatile java.lang.Object version_;
  /**
   * <code>string version = 10;</code>
   */
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 10;</code>
   */
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < credentialRequests_.size(); i++) {
      output.writeMessage(1, credentialRequests_.get(i));
    }
    if (!getHolderAppUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, holderAppUuid_);
    }
    if (!getVerifierBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, verifier_);
    }
    if (createdAt_ != null) {
      output.writeMessage(4, getCreatedAt());
    }
    if (updatedAt_ != null) {
      output.writeMessage(5, getUpdatedAt());
    }
    if (expiresAt_ != null) {
      output.writeMessage(6, getExpiresAt());
    }
    if (!getMetadataBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, metadata_);
    }
    if (!getUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, uuid_);
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, id_);
    }
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, version_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < credentialRequests_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, credentialRequests_.get(i));
    }
    if (!getHolderAppUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, holderAppUuid_);
    }
    if (!getVerifierBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, verifier_);
    }
    if (createdAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCreatedAt());
    }
    if (updatedAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getUpdatedAt());
    }
    if (expiresAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getExpiresAt());
    }
    if (!getMetadataBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, metadata_);
    }
    if (!getUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, uuid_);
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, id_);
    }
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, version_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof presentation.v1.UnsignedPresentationRequest)) {
      return super.equals(obj);
    }
    presentation.v1.UnsignedPresentationRequest other = (presentation.v1.UnsignedPresentationRequest) obj;

    boolean result = true;
    result = result && getCredentialRequestsList()
        .equals(other.getCredentialRequestsList());
    result = result && getHolderAppUuid()
        .equals(other.getHolderAppUuid());
    result = result && getVerifier()
        .equals(other.getVerifier());
    result = result && (hasCreatedAt() == other.hasCreatedAt());
    if (hasCreatedAt()) {
      result = result && getCreatedAt()
          .equals(other.getCreatedAt());
    }
    result = result && (hasUpdatedAt() == other.hasUpdatedAt());
    if (hasUpdatedAt()) {
      result = result && getUpdatedAt()
          .equals(other.getUpdatedAt());
    }
    result = result && (hasExpiresAt() == other.hasExpiresAt());
    if (hasExpiresAt()) {
      result = result && getExpiresAt()
          .equals(other.getExpiresAt());
    }
    result = result && getMetadata()
        .equals(other.getMetadata());
    result = result && getUuid()
        .equals(other.getUuid());
    result = result && getId()
        .equals(other.getId());
    result = result && getVersion()
        .equals(other.getVersion());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCredentialRequestsCount() > 0) {
      hash = (37 * hash) + CREDENTIAL_REQUESTS_FIELD_NUMBER;
      hash = (53 * hash) + getCredentialRequestsList().hashCode();
    }
    hash = (37 * hash) + HOLDER_APP_UUID_FIELD_NUMBER;
    hash = (53 * hash) + getHolderAppUuid().hashCode();
    hash = (37 * hash) + VERIFIER_FIELD_NUMBER;
    hash = (53 * hash) + getVerifier().hashCode();
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    if (hasUpdatedAt()) {
      hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedAt().hashCode();
    }
    if (hasExpiresAt()) {
      hash = (37 * hash) + EXPIRES_AT_FIELD_NUMBER;
      hash = (53 * hash) + getExpiresAt().hashCode();
    }
    hash = (37 * hash) + METADATA_FIELD_NUMBER;
    hash = (53 * hash) + getMetadata().hashCode();
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static presentation.v1.UnsignedPresentationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static presentation.v1.UnsignedPresentationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static presentation.v1.UnsignedPresentationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static presentation.v1.UnsignedPresentationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static presentation.v1.UnsignedPresentationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static presentation.v1.UnsignedPresentationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static presentation.v1.UnsignedPresentationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static presentation.v1.UnsignedPresentationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static presentation.v1.UnsignedPresentationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static presentation.v1.UnsignedPresentationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static presentation.v1.UnsignedPresentationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static presentation.v1.UnsignedPresentationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(presentation.v1.UnsignedPresentationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * Encapsulates request attributes for the purposes of requesting presentation of credentials.
   * </pre>
   *
   * Protobuf type {@code presentation.v1.UnsignedPresentationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:presentation.v1.UnsignedPresentationRequest)
      presentation.v1.UnsignedPresentationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return presentation.v1.PresentationProto.internal_static_presentation_v1_UnsignedPresentationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return presentation.v1.PresentationProto.internal_static_presentation_v1_UnsignedPresentationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              presentation.v1.UnsignedPresentationRequest.class, presentation.v1.UnsignedPresentationRequest.Builder.class);
    }

    // Construct using presentation.v1.UnsignedPresentationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCredentialRequestsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (credentialRequestsBuilder_ == null) {
        credentialRequests_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        credentialRequestsBuilder_.clear();
      }
      holderAppUuid_ = "";

      verifier_ = "";

      if (createdAtBuilder_ == null) {
        createdAt_ = null;
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }
      if (updatedAtBuilder_ == null) {
        updatedAt_ = null;
      } else {
        updatedAt_ = null;
        updatedAtBuilder_ = null;
      }
      if (expiresAtBuilder_ == null) {
        expiresAt_ = null;
      } else {
        expiresAt_ = null;
        expiresAtBuilder_ = null;
      }
      metadata_ = "";

      uuid_ = "";

      id_ = "";

      version_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return presentation.v1.PresentationProto.internal_static_presentation_v1_UnsignedPresentationRequest_descriptor;
    }

    @java.lang.Override
    public presentation.v1.UnsignedPresentationRequest getDefaultInstanceForType() {
      return presentation.v1.UnsignedPresentationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public presentation.v1.UnsignedPresentationRequest build() {
      presentation.v1.UnsignedPresentationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public presentation.v1.UnsignedPresentationRequest buildPartial() {
      presentation.v1.UnsignedPresentationRequest result = new presentation.v1.UnsignedPresentationRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (credentialRequestsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          credentialRequests_ = java.util.Collections.unmodifiableList(credentialRequests_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.credentialRequests_ = credentialRequests_;
      } else {
        result.credentialRequests_ = credentialRequestsBuilder_.build();
      }
      result.holderAppUuid_ = holderAppUuid_;
      result.verifier_ = verifier_;
      if (createdAtBuilder_ == null) {
        result.createdAt_ = createdAt_;
      } else {
        result.createdAt_ = createdAtBuilder_.build();
      }
      if (updatedAtBuilder_ == null) {
        result.updatedAt_ = updatedAt_;
      } else {
        result.updatedAt_ = updatedAtBuilder_.build();
      }
      if (expiresAtBuilder_ == null) {
        result.expiresAt_ = expiresAt_;
      } else {
        result.expiresAt_ = expiresAtBuilder_.build();
      }
      result.metadata_ = metadata_;
      result.uuid_ = uuid_;
      result.id_ = id_;
      result.version_ = version_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof presentation.v1.UnsignedPresentationRequest) {
        return mergeFrom((presentation.v1.UnsignedPresentationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(presentation.v1.UnsignedPresentationRequest other) {
      if (other == presentation.v1.UnsignedPresentationRequest.getDefaultInstance()) return this;
      if (credentialRequestsBuilder_ == null) {
        if (!other.credentialRequests_.isEmpty()) {
          if (credentialRequests_.isEmpty()) {
            credentialRequests_ = other.credentialRequests_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCredentialRequestsIsMutable();
            credentialRequests_.addAll(other.credentialRequests_);
          }
          onChanged();
        }
      } else {
        if (!other.credentialRequests_.isEmpty()) {
          if (credentialRequestsBuilder_.isEmpty()) {
            credentialRequestsBuilder_.dispose();
            credentialRequestsBuilder_ = null;
            credentialRequests_ = other.credentialRequests_;
            bitField0_ = (bitField0_ & ~0x00000001);
            credentialRequestsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCredentialRequestsFieldBuilder() : null;
          } else {
            credentialRequestsBuilder_.addAllMessages(other.credentialRequests_);
          }
        }
      }
      if (!other.getHolderAppUuid().isEmpty()) {
        holderAppUuid_ = other.holderAppUuid_;
        onChanged();
      }
      if (!other.getVerifier().isEmpty()) {
        verifier_ = other.verifier_;
        onChanged();
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      if (other.hasUpdatedAt()) {
        mergeUpdatedAt(other.getUpdatedAt());
      }
      if (other.hasExpiresAt()) {
        mergeExpiresAt(other.getExpiresAt());
      }
      if (!other.getMetadata().isEmpty()) {
        metadata_ = other.metadata_;
        onChanged();
      }
      if (!other.getUuid().isEmpty()) {
        uuid_ = other.uuid_;
        onChanged();
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      presentation.v1.UnsignedPresentationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (presentation.v1.UnsignedPresentationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<credential.v1.CredentialRequest> credentialRequests_ =
      java.util.Collections.emptyList();
    private void ensureCredentialRequestsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        credentialRequests_ = new java.util.ArrayList<credential.v1.CredentialRequest>(credentialRequests_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        credential.v1.CredentialRequest, credential.v1.CredentialRequest.Builder, credential.v1.CredentialRequestOrBuilder> credentialRequestsBuilder_;

    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public java.util.List<credential.v1.CredentialRequest> getCredentialRequestsList() {
      if (credentialRequestsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(credentialRequests_);
      } else {
        return credentialRequestsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public int getCredentialRequestsCount() {
      if (credentialRequestsBuilder_ == null) {
        return credentialRequests_.size();
      } else {
        return credentialRequestsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public credential.v1.CredentialRequest getCredentialRequests(int index) {
      if (credentialRequestsBuilder_ == null) {
        return credentialRequests_.get(index);
      } else {
        return credentialRequestsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public Builder setCredentialRequests(
        int index, credential.v1.CredentialRequest value) {
      if (credentialRequestsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCredentialRequestsIsMutable();
        credentialRequests_.set(index, value);
        onChanged();
      } else {
        credentialRequestsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public Builder setCredentialRequests(
        int index, credential.v1.CredentialRequest.Builder builderForValue) {
      if (credentialRequestsBuilder_ == null) {
        ensureCredentialRequestsIsMutable();
        credentialRequests_.set(index, builderForValue.build());
        onChanged();
      } else {
        credentialRequestsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public Builder addCredentialRequests(credential.v1.CredentialRequest value) {
      if (credentialRequestsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCredentialRequestsIsMutable();
        credentialRequests_.add(value);
        onChanged();
      } else {
        credentialRequestsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public Builder addCredentialRequests(
        int index, credential.v1.CredentialRequest value) {
      if (credentialRequestsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCredentialRequestsIsMutable();
        credentialRequests_.add(index, value);
        onChanged();
      } else {
        credentialRequestsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public Builder addCredentialRequests(
        credential.v1.CredentialRequest.Builder builderForValue) {
      if (credentialRequestsBuilder_ == null) {
        ensureCredentialRequestsIsMutable();
        credentialRequests_.add(builderForValue.build());
        onChanged();
      } else {
        credentialRequestsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public Builder addCredentialRequests(
        int index, credential.v1.CredentialRequest.Builder builderForValue) {
      if (credentialRequestsBuilder_ == null) {
        ensureCredentialRequestsIsMutable();
        credentialRequests_.add(index, builderForValue.build());
        onChanged();
      } else {
        credentialRequestsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public Builder addAllCredentialRequests(
        java.lang.Iterable<? extends credential.v1.CredentialRequest> values) {
      if (credentialRequestsBuilder_ == null) {
        ensureCredentialRequestsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, credentialRequests_);
        onChanged();
      } else {
        credentialRequestsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public Builder clearCredentialRequests() {
      if (credentialRequestsBuilder_ == null) {
        credentialRequests_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        credentialRequestsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public Builder removeCredentialRequests(int index) {
      if (credentialRequestsBuilder_ == null) {
        ensureCredentialRequestsIsMutable();
        credentialRequests_.remove(index);
        onChanged();
      } else {
        credentialRequestsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public credential.v1.CredentialRequest.Builder getCredentialRequestsBuilder(
        int index) {
      return getCredentialRequestsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public credential.v1.CredentialRequestOrBuilder getCredentialRequestsOrBuilder(
        int index) {
      if (credentialRequestsBuilder_ == null) {
        return credentialRequests_.get(index);  } else {
        return credentialRequestsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public java.util.List<? extends credential.v1.CredentialRequestOrBuilder> 
         getCredentialRequestsOrBuilderList() {
      if (credentialRequestsBuilder_ != null) {
        return credentialRequestsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(credentialRequests_);
      }
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public credential.v1.CredentialRequest.Builder addCredentialRequestsBuilder() {
      return getCredentialRequestsFieldBuilder().addBuilder(
          credential.v1.CredentialRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public credential.v1.CredentialRequest.Builder addCredentialRequestsBuilder(
        int index) {
      return getCredentialRequestsFieldBuilder().addBuilder(
          index, credential.v1.CredentialRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .credential.v1.CredentialRequest credential_requests = 1;</code>
     */
    public java.util.List<credential.v1.CredentialRequest.Builder> 
         getCredentialRequestsBuilderList() {
      return getCredentialRequestsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        credential.v1.CredentialRequest, credential.v1.CredentialRequest.Builder, credential.v1.CredentialRequestOrBuilder> 
        getCredentialRequestsFieldBuilder() {
      if (credentialRequestsBuilder_ == null) {
        credentialRequestsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            credential.v1.CredentialRequest, credential.v1.CredentialRequest.Builder, credential.v1.CredentialRequestOrBuilder>(
                credentialRequests_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        credentialRequests_ = null;
      }
      return credentialRequestsBuilder_;
    }

    private java.lang.Object holderAppUuid_ = "";
    /**
     * <code>string holder_app_uuid = 2;</code>
     */
    public java.lang.String getHolderAppUuid() {
      java.lang.Object ref = holderAppUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        holderAppUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string holder_app_uuid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHolderAppUuidBytes() {
      java.lang.Object ref = holderAppUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        holderAppUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string holder_app_uuid = 2;</code>
     */
    public Builder setHolderAppUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      holderAppUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string holder_app_uuid = 2;</code>
     */
    public Builder clearHolderAppUuid() {
      
      holderAppUuid_ = getDefaultInstance().getHolderAppUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string holder_app_uuid = 2;</code>
     */
    public Builder setHolderAppUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      holderAppUuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object verifier_ = "";
    /**
     * <code>string verifier = 3;</code>
     */
    public java.lang.String getVerifier() {
      java.lang.Object ref = verifier_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        verifier_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string verifier = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVerifierBytes() {
      java.lang.Object ref = verifier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string verifier = 3;</code>
     */
    public Builder setVerifier(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      verifier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string verifier = 3;</code>
     */
    public Builder clearVerifier() {
      
      verifier_ = getDefaultInstance().getVerifier();
      onChanged();
      return this;
    }
    /**
     * <code>string verifier = 3;</code>
     */
    public Builder setVerifierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      verifier_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdAt_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    public boolean hasCreatedAt() {
      return createdAtBuilder_ != null || createdAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
        onChanged();
      } else {
        createdAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
        onChanged();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (createdAt_ != null) {
          createdAt_ =
            com.google.protobuf.Timestamp.newBuilder(createdAt_).mergeFrom(value).buildPartial();
        } else {
          createdAt_ = value;
        }
        onChanged();
      } else {
        createdAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    public Builder clearCreatedAt() {
      if (createdAtBuilder_ == null) {
        createdAt_ = null;
        onChanged();
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private com.google.protobuf.Timestamp updatedAt_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp updated_at = 5;</code>
     */
    public boolean hasUpdatedAt() {
      return updatedAtBuilder_ != null || updatedAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 5;</code>
     */
    public com.google.protobuf.Timestamp getUpdatedAt() {
      if (updatedAtBuilder_ == null) {
        return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      } else {
        return updatedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 5;</code>
     */
    public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updatedAt_ = value;
        onChanged();
      } else {
        updatedAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 5;</code>
     */
    public Builder setUpdatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updatedAtBuilder_ == null) {
        updatedAt_ = builderForValue.build();
        onChanged();
      } else {
        updatedAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 5;</code>
     */
    public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (updatedAt_ != null) {
          updatedAt_ =
            com.google.protobuf.Timestamp.newBuilder(updatedAt_).mergeFrom(value).buildPartial();
        } else {
          updatedAt_ = value;
        }
        onChanged();
      } else {
        updatedAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 5;</code>
     */
    public Builder clearUpdatedAt() {
      if (updatedAtBuilder_ == null) {
        updatedAt_ = null;
        onChanged();
      } else {
        updatedAt_ = null;
        updatedAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
      
      onChanged();
      return getUpdatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      if (updatedAtBuilder_ != null) {
        return updatedAtBuilder_.getMessageOrBuilder();
      } else {
        return updatedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUpdatedAtFieldBuilder() {
      if (updatedAtBuilder_ == null) {
        updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdatedAt(),
                getParentForChildren(),
                isClean());
        updatedAt_ = null;
      }
      return updatedAtBuilder_;
    }

    private com.google.protobuf.Timestamp expiresAt_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expiresAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6;</code>
     */
    public boolean hasExpiresAt() {
      return expiresAtBuilder_ != null || expiresAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6;</code>
     */
    public com.google.protobuf.Timestamp getExpiresAt() {
      if (expiresAtBuilder_ == null) {
        return expiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
      } else {
        return expiresAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6;</code>
     */
    public Builder setExpiresAt(com.google.protobuf.Timestamp value) {
      if (expiresAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expiresAt_ = value;
        onChanged();
      } else {
        expiresAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6;</code>
     */
    public Builder setExpiresAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expiresAtBuilder_ == null) {
        expiresAt_ = builderForValue.build();
        onChanged();
      } else {
        expiresAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6;</code>
     */
    public Builder mergeExpiresAt(com.google.protobuf.Timestamp value) {
      if (expiresAtBuilder_ == null) {
        if (expiresAt_ != null) {
          expiresAt_ =
            com.google.protobuf.Timestamp.newBuilder(expiresAt_).mergeFrom(value).buildPartial();
        } else {
          expiresAt_ = value;
        }
        onChanged();
      } else {
        expiresAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6;</code>
     */
    public Builder clearExpiresAt() {
      if (expiresAtBuilder_ == null) {
        expiresAt_ = null;
        onChanged();
      } else {
        expiresAt_ = null;
        expiresAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getExpiresAtBuilder() {
      
      onChanged();
      return getExpiresAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getExpiresAtOrBuilder() {
      if (expiresAtBuilder_ != null) {
        return expiresAtBuilder_.getMessageOrBuilder();
      } else {
        return expiresAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getExpiresAtFieldBuilder() {
      if (expiresAtBuilder_ == null) {
        expiresAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getExpiresAt(),
                getParentForChildren(),
                isClean());
        expiresAt_ = null;
      }
      return expiresAtBuilder_;
    }

    private java.lang.Object metadata_ = "";
    /**
     * <pre>
     * a string representation of an ambiguous object. Note: the Any type does not work because still needs a scheme (but can be assigned dymanically) &amp; Struct does not work becuase not determinsitcally serialzied across langauges
     * </pre>
     *
     * <code>string metadata = 7;</code>
     */
    public java.lang.String getMetadata() {
      java.lang.Object ref = metadata_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metadata_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * a string representation of an ambiguous object. Note: the Any type does not work because still needs a scheme (but can be assigned dymanically) &amp; Struct does not work becuase not determinsitcally serialzied across langauges
     * </pre>
     *
     * <code>string metadata = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMetadataBytes() {
      java.lang.Object ref = metadata_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metadata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * a string representation of an ambiguous object. Note: the Any type does not work because still needs a scheme (but can be assigned dymanically) &amp; Struct does not work becuase not determinsitcally serialzied across langauges
     * </pre>
     *
     * <code>string metadata = 7;</code>
     */
    public Builder setMetadata(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      metadata_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * a string representation of an ambiguous object. Note: the Any type does not work because still needs a scheme (but can be assigned dymanically) &amp; Struct does not work becuase not determinsitcally serialzied across langauges
     * </pre>
     *
     * <code>string metadata = 7;</code>
     */
    public Builder clearMetadata() {
      
      metadata_ = getDefaultInstance().getMetadata();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * a string representation of an ambiguous object. Note: the Any type does not work because still needs a scheme (but can be assigned dymanically) &amp; Struct does not work becuase not determinsitcally serialzied across langauges
     * </pre>
     *
     * <code>string metadata = 7;</code>
     */
    public Builder setMetadataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      metadata_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 8;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uuid = 8;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uuid = 8;</code>
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 8;</code>
     */
    public Builder clearUuid() {
      
      uuid_ = getDefaultInstance().getUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 8;</code>
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * an indentifier for related presetnation requests across versions
     * </pre>
     *
     * <code>string id = 9;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * an indentifier for related presetnation requests across versions
     * </pre>
     *
     * <code>string id = 9;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * an indentifier for related presetnation requests across versions
     * </pre>
     *
     * <code>string id = 9;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * an indentifier for related presetnation requests across versions
     * </pre>
     *
     * <code>string id = 9;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * an indentifier for related presetnation requests across versions
     * </pre>
     *
     * <code>string id = 9;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 10;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 10;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 10;</code>
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 10;</code>
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string version = 10;</code>
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:presentation.v1.UnsignedPresentationRequest)
  }

  // @@protoc_insertion_point(class_scope:presentation.v1.UnsignedPresentationRequest)
  private static final presentation.v1.UnsignedPresentationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new presentation.v1.UnsignedPresentationRequest();
  }

  public static presentation.v1.UnsignedPresentationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UnsignedPresentationRequest>
      PARSER = new com.google.protobuf.AbstractParser<UnsignedPresentationRequest>() {
    @java.lang.Override
    public UnsignedPresentationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UnsignedPresentationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UnsignedPresentationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UnsignedPresentationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public presentation.v1.UnsignedPresentationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

