// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: credential.proto

package credential.v1;

public interface CredentialStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:credential.v1.CredentialStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
