// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: credential.proto

package credential.v1;

/**
 * <pre>
 **
 * Object that encapsulates Credential information requested.
 * </pre>
 *
 * Protobuf type {@code credential.v1.CredentialRequest}
 */
public  final class CredentialRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:credential.v1.CredentialRequest)
    CredentialRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CredentialRequest.newBuilder() to construct.
  private CredentialRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CredentialRequest() {
    type_ = "";
    issuers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    required_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CredentialRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              issuers_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            issuers_.add(s);
            break;
          }
          case 24: {

            required_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        issuers_ = issuers_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return credential.v1.CredentialProto.internal_static_credential_v1_CredentialRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return credential.v1.CredentialProto.internal_static_credential_v1_CredentialRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            credential.v1.CredentialRequest.class, credential.v1.CredentialRequest.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <pre>
   * the string matching the desire credential type
   * </pre>
   *
   * <code>string type = 1;</code>
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * the string matching the desire credential type
   * </pre>
   *
   * <code>string type = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISSUERS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList issuers_;
  /**
   * <pre>
   * list of acceptable issuer DIDs that have issued the credential
   * </pre>
   *
   * <code>repeated string issuers = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getIssuersList() {
    return issuers_;
  }
  /**
   * <pre>
   * list of acceptable issuer DIDs that have issued the credential
   * </pre>
   *
   * <code>repeated string issuers = 2;</code>
   */
  public int getIssuersCount() {
    return issuers_.size();
  }
  /**
   * <pre>
   * list of acceptable issuer DIDs that have issued the credential
   * </pre>
   *
   * <code>repeated string issuers = 2;</code>
   */
  public java.lang.String getIssuers(int index) {
    return issuers_.get(index);
  }
  /**
   * <pre>
   * list of acceptable issuer DIDs that have issued the credential
   * </pre>
   *
   * <code>repeated string issuers = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIssuersBytes(int index) {
    return issuers_.getByteString(index);
  }

  public static final int REQUIRED_FIELD_NUMBER = 3;
  private boolean required_;
  /**
   * <pre>
   * to denote wether this particular credential is required in response to the PresentationRequest. Defaults behavior resolves this to true.
   * </pre>
   *
   * <code>bool required = 3;</code>
   */
  public boolean getRequired() {
    return required_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    for (int i = 0; i < issuers_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, issuers_.getRaw(i));
    }
    if (required_ != false) {
      output.writeBool(3, required_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < issuers_.size(); i++) {
        dataSize += computeStringSizeNoTag(issuers_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getIssuersList().size();
    }
    if (required_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, required_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof credential.v1.CredentialRequest)) {
      return super.equals(obj);
    }
    credential.v1.CredentialRequest other = (credential.v1.CredentialRequest) obj;

    boolean result = true;
    result = result && getType()
        .equals(other.getType());
    result = result && getIssuersList()
        .equals(other.getIssuersList());
    result = result && (getRequired()
        == other.getRequired());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    if (getIssuersCount() > 0) {
      hash = (37 * hash) + ISSUERS_FIELD_NUMBER;
      hash = (53 * hash) + getIssuersList().hashCode();
    }
    hash = (37 * hash) + REQUIRED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRequired());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static credential.v1.CredentialRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static credential.v1.CredentialRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static credential.v1.CredentialRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static credential.v1.CredentialRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static credential.v1.CredentialRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static credential.v1.CredentialRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static credential.v1.CredentialRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static credential.v1.CredentialRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static credential.v1.CredentialRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static credential.v1.CredentialRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static credential.v1.CredentialRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static credential.v1.CredentialRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(credential.v1.CredentialRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * Object that encapsulates Credential information requested.
   * </pre>
   *
   * Protobuf type {@code credential.v1.CredentialRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:credential.v1.CredentialRequest)
      credential.v1.CredentialRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return credential.v1.CredentialProto.internal_static_credential_v1_CredentialRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return credential.v1.CredentialProto.internal_static_credential_v1_CredentialRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              credential.v1.CredentialRequest.class, credential.v1.CredentialRequest.Builder.class);
    }

    // Construct using credential.v1.CredentialRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = "";

      issuers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      required_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return credential.v1.CredentialProto.internal_static_credential_v1_CredentialRequest_descriptor;
    }

    @java.lang.Override
    public credential.v1.CredentialRequest getDefaultInstanceForType() {
      return credential.v1.CredentialRequest.getDefaultInstance();
    }

    @java.lang.Override
    public credential.v1.CredentialRequest build() {
      credential.v1.CredentialRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public credential.v1.CredentialRequest buildPartial() {
      credential.v1.CredentialRequest result = new credential.v1.CredentialRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.type_ = type_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        issuers_ = issuers_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.issuers_ = issuers_;
      result.required_ = required_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof credential.v1.CredentialRequest) {
        return mergeFrom((credential.v1.CredentialRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(credential.v1.CredentialRequest other) {
      if (other == credential.v1.CredentialRequest.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.issuers_.isEmpty()) {
        if (issuers_.isEmpty()) {
          issuers_ = other.issuers_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureIssuersIsMutable();
          issuers_.addAll(other.issuers_);
        }
        onChanged();
      }
      if (other.getRequired() != false) {
        setRequired(other.getRequired());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      credential.v1.CredentialRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (credential.v1.CredentialRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object type_ = "";
    /**
     * <pre>
     * the string matching the desire credential type
     * </pre>
     *
     * <code>string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * the string matching the desire credential type
     * </pre>
     *
     * <code>string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * the string matching the desire credential type
     * </pre>
     *
     * <code>string type = 1;</code>
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the string matching the desire credential type
     * </pre>
     *
     * <code>string type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * the string matching the desire credential type
     * </pre>
     *
     * <code>string type = 1;</code>
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList issuers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureIssuersIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        issuers_ = new com.google.protobuf.LazyStringArrayList(issuers_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * list of acceptable issuer DIDs that have issued the credential
     * </pre>
     *
     * <code>repeated string issuers = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getIssuersList() {
      return issuers_.getUnmodifiableView();
    }
    /**
     * <pre>
     * list of acceptable issuer DIDs that have issued the credential
     * </pre>
     *
     * <code>repeated string issuers = 2;</code>
     */
    public int getIssuersCount() {
      return issuers_.size();
    }
    /**
     * <pre>
     * list of acceptable issuer DIDs that have issued the credential
     * </pre>
     *
     * <code>repeated string issuers = 2;</code>
     */
    public java.lang.String getIssuers(int index) {
      return issuers_.get(index);
    }
    /**
     * <pre>
     * list of acceptable issuer DIDs that have issued the credential
     * </pre>
     *
     * <code>repeated string issuers = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIssuersBytes(int index) {
      return issuers_.getByteString(index);
    }
    /**
     * <pre>
     * list of acceptable issuer DIDs that have issued the credential
     * </pre>
     *
     * <code>repeated string issuers = 2;</code>
     */
    public Builder setIssuers(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIssuersIsMutable();
      issuers_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of acceptable issuer DIDs that have issued the credential
     * </pre>
     *
     * <code>repeated string issuers = 2;</code>
     */
    public Builder addIssuers(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIssuersIsMutable();
      issuers_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of acceptable issuer DIDs that have issued the credential
     * </pre>
     *
     * <code>repeated string issuers = 2;</code>
     */
    public Builder addAllIssuers(
        java.lang.Iterable<java.lang.String> values) {
      ensureIssuersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, issuers_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of acceptable issuer DIDs that have issued the credential
     * </pre>
     *
     * <code>repeated string issuers = 2;</code>
     */
    public Builder clearIssuers() {
      issuers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * list of acceptable issuer DIDs that have issued the credential
     * </pre>
     *
     * <code>repeated string issuers = 2;</code>
     */
    public Builder addIssuersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureIssuersIsMutable();
      issuers_.add(value);
      onChanged();
      return this;
    }

    private boolean required_ ;
    /**
     * <pre>
     * to denote wether this particular credential is required in response to the PresentationRequest. Defaults behavior resolves this to true.
     * </pre>
     *
     * <code>bool required = 3;</code>
     */
    public boolean getRequired() {
      return required_;
    }
    /**
     * <pre>
     * to denote wether this particular credential is required in response to the PresentationRequest. Defaults behavior resolves this to true.
     * </pre>
     *
     * <code>bool required = 3;</code>
     */
    public Builder setRequired(boolean value) {
      
      required_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * to denote wether this particular credential is required in response to the PresentationRequest. Defaults behavior resolves this to true.
     * </pre>
     *
     * <code>bool required = 3;</code>
     */
    public Builder clearRequired() {
      
      required_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:credential.v1.CredentialRequest)
  }

  // @@protoc_insertion_point(class_scope:credential.v1.CredentialRequest)
  private static final credential.v1.CredentialRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new credential.v1.CredentialRequest();
  }

  public static credential.v1.CredentialRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CredentialRequest>
      PARSER = new com.google.protobuf.AbstractParser<CredentialRequest>() {
    @java.lang.Override
    public CredentialRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CredentialRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CredentialRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CredentialRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public credential.v1.CredentialRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

