// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: credential.proto

package credential.v1;

/**
 * <pre>
 **
 * Object to encapsulate relevant credential information.
 * </pre>
 *
 * Protobuf type {@code credential.v1.UnsignedCredential}
 */
public  final class UnsignedCredential extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:credential.v1.UnsignedCredential)
    UnsignedCredentialOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UnsignedCredential.newBuilder() to construct.
  private UnsignedCredential(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UnsignedCredential() {
    context_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    credentialSubject_ = "";
    issuer_ = "";
    type_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    id_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UnsignedCredential(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              context_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            context_.add(s);
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            credentialSubject_ = s;
            break;
          }
          case 26: {
            credential.v1.CredentialStatus.Builder subBuilder = null;
            if (credentialStatus_ != null) {
              subBuilder = credentialStatus_.toBuilder();
            }
            credentialStatus_ = input.readMessage(credential.v1.CredentialStatus.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(credentialStatus_);
              credentialStatus_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            issuer_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              type_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000010;
            }
            type_.add(s);
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 58: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (issuanceDate_ != null) {
              subBuilder = issuanceDate_.toBuilder();
            }
            issuanceDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(issuanceDate_);
              issuanceDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 130: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (expirationDate_ != null) {
              subBuilder = expirationDate_.toBuilder();
            }
            expirationDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(expirationDate_);
              expirationDate_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        context_ = context_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        type_ = type_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return credential.v1.CredentialProto.internal_static_credential_v1_UnsignedCredential_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return credential.v1.CredentialProto.internal_static_credential_v1_UnsignedCredential_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            credential.v1.UnsignedCredential.class, credential.v1.UnsignedCredential.Builder.class);
  }

  private int bitField0_;
  public static final int CONTEXT_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList context_;
  /**
   * <code>repeated string context = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getContextList() {
    return context_;
  }
  /**
   * <code>repeated string context = 1;</code>
   */
  public int getContextCount() {
    return context_.size();
  }
  /**
   * <code>repeated string context = 1;</code>
   */
  public java.lang.String getContext(int index) {
    return context_.get(index);
  }
  /**
   * <code>repeated string context = 1;</code>
   */
  public com.google.protobuf.ByteString
      getContextBytes(int index) {
    return context_.getByteString(index);
  }

  public static final int CREDENTIAL_SUBJECT_FIELD_NUMBER = 2;
  private volatile java.lang.Object credentialSubject_;
  /**
   * <code>string credential_subject = 2;</code>
   */
  public java.lang.String getCredentialSubject() {
    java.lang.Object ref = credentialSubject_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      credentialSubject_ = s;
      return s;
    }
  }
  /**
   * <code>string credential_subject = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCredentialSubjectBytes() {
    java.lang.Object ref = credentialSubject_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      credentialSubject_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREDENTIAL_STATUS_FIELD_NUMBER = 3;
  private credential.v1.CredentialStatus credentialStatus_;
  /**
   * <code>.credential.v1.CredentialStatus credential_status = 3;</code>
   */
  public boolean hasCredentialStatus() {
    return credentialStatus_ != null;
  }
  /**
   * <code>.credential.v1.CredentialStatus credential_status = 3;</code>
   */
  public credential.v1.CredentialStatus getCredentialStatus() {
    return credentialStatus_ == null ? credential.v1.CredentialStatus.getDefaultInstance() : credentialStatus_;
  }
  /**
   * <code>.credential.v1.CredentialStatus credential_status = 3;</code>
   */
  public credential.v1.CredentialStatusOrBuilder getCredentialStatusOrBuilder() {
    return getCredentialStatus();
  }

  public static final int ISSUER_FIELD_NUMBER = 4;
  private volatile java.lang.Object issuer_;
  /**
   * <code>string issuer = 4;</code>
   */
  public java.lang.String getIssuer() {
    java.lang.Object ref = issuer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      issuer_ = s;
      return s;
    }
  }
  /**
   * <code>string issuer = 4;</code>
   */
  public com.google.protobuf.ByteString
      getIssuerBytes() {
    java.lang.Object ref = issuer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      issuer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList type_;
  /**
   * <code>repeated string type = 5;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getTypeList() {
    return type_;
  }
  /**
   * <code>repeated string type = 5;</code>
   */
  public int getTypeCount() {
    return type_.size();
  }
  /**
   * <code>repeated string type = 5;</code>
   */
  public java.lang.String getType(int index) {
    return type_.get(index);
  }
  /**
   * <code>repeated string type = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes(int index) {
    return type_.getByteString(index);
  }

  public static final int ID_FIELD_NUMBER = 6;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 6;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 6;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISSUANCE_DATE_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp issuanceDate_;
  /**
   * <code>.google.protobuf.Timestamp issuance_date = 7;</code>
   */
  public boolean hasIssuanceDate() {
    return issuanceDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp issuance_date = 7;</code>
   */
  public com.google.protobuf.Timestamp getIssuanceDate() {
    return issuanceDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : issuanceDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp issuance_date = 7;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getIssuanceDateOrBuilder() {
    return getIssuanceDate();
  }

  public static final int EXPIRATION_DATE_FIELD_NUMBER = 16;
  private com.google.protobuf.Timestamp expirationDate_;
  /**
   * <pre>
   * optional in the ts types
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expiration_date = 16;</code>
   */
  public boolean hasExpirationDate() {
    return expirationDate_ != null;
  }
  /**
   * <pre>
   * optional in the ts types
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expiration_date = 16;</code>
   */
  public com.google.protobuf.Timestamp getExpirationDate() {
    return expirationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expirationDate_;
  }
  /**
   * <pre>
   * optional in the ts types
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expiration_date = 16;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getExpirationDateOrBuilder() {
    return getExpirationDate();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < context_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, context_.getRaw(i));
    }
    if (!getCredentialSubjectBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, credentialSubject_);
    }
    if (credentialStatus_ != null) {
      output.writeMessage(3, getCredentialStatus());
    }
    if (!getIssuerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, issuer_);
    }
    for (int i = 0; i < type_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, type_.getRaw(i));
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, id_);
    }
    if (issuanceDate_ != null) {
      output.writeMessage(7, getIssuanceDate());
    }
    if (expirationDate_ != null) {
      output.writeMessage(16, getExpirationDate());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < context_.size(); i++) {
        dataSize += computeStringSizeNoTag(context_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getContextList().size();
    }
    if (!getCredentialSubjectBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, credentialSubject_);
    }
    if (credentialStatus_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getCredentialStatus());
    }
    if (!getIssuerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, issuer_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < type_.size(); i++) {
        dataSize += computeStringSizeNoTag(type_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTypeList().size();
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, id_);
    }
    if (issuanceDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getIssuanceDate());
    }
    if (expirationDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, getExpirationDate());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof credential.v1.UnsignedCredential)) {
      return super.equals(obj);
    }
    credential.v1.UnsignedCredential other = (credential.v1.UnsignedCredential) obj;

    boolean result = true;
    result = result && getContextList()
        .equals(other.getContextList());
    result = result && getCredentialSubject()
        .equals(other.getCredentialSubject());
    result = result && (hasCredentialStatus() == other.hasCredentialStatus());
    if (hasCredentialStatus()) {
      result = result && getCredentialStatus()
          .equals(other.getCredentialStatus());
    }
    result = result && getIssuer()
        .equals(other.getIssuer());
    result = result && getTypeList()
        .equals(other.getTypeList());
    result = result && getId()
        .equals(other.getId());
    result = result && (hasIssuanceDate() == other.hasIssuanceDate());
    if (hasIssuanceDate()) {
      result = result && getIssuanceDate()
          .equals(other.getIssuanceDate());
    }
    result = result && (hasExpirationDate() == other.hasExpirationDate());
    if (hasExpirationDate()) {
      result = result && getExpirationDate()
          .equals(other.getExpirationDate());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getContextCount() > 0) {
      hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getContextList().hashCode();
    }
    hash = (37 * hash) + CREDENTIAL_SUBJECT_FIELD_NUMBER;
    hash = (53 * hash) + getCredentialSubject().hashCode();
    if (hasCredentialStatus()) {
      hash = (37 * hash) + CREDENTIAL_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getCredentialStatus().hashCode();
    }
    hash = (37 * hash) + ISSUER_FIELD_NUMBER;
    hash = (53 * hash) + getIssuer().hashCode();
    if (getTypeCount() > 0) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTypeList().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasIssuanceDate()) {
      hash = (37 * hash) + ISSUANCE_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getIssuanceDate().hashCode();
    }
    if (hasExpirationDate()) {
      hash = (37 * hash) + EXPIRATION_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getExpirationDate().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static credential.v1.UnsignedCredential parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static credential.v1.UnsignedCredential parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static credential.v1.UnsignedCredential parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static credential.v1.UnsignedCredential parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static credential.v1.UnsignedCredential parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static credential.v1.UnsignedCredential parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static credential.v1.UnsignedCredential parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static credential.v1.UnsignedCredential parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static credential.v1.UnsignedCredential parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static credential.v1.UnsignedCredential parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static credential.v1.UnsignedCredential parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static credential.v1.UnsignedCredential parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(credential.v1.UnsignedCredential prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * Object to encapsulate relevant credential information.
   * </pre>
   *
   * Protobuf type {@code credential.v1.UnsignedCredential}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:credential.v1.UnsignedCredential)
      credential.v1.UnsignedCredentialOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return credential.v1.CredentialProto.internal_static_credential_v1_UnsignedCredential_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return credential.v1.CredentialProto.internal_static_credential_v1_UnsignedCredential_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              credential.v1.UnsignedCredential.class, credential.v1.UnsignedCredential.Builder.class);
    }

    // Construct using credential.v1.UnsignedCredential.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      context_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      credentialSubject_ = "";

      if (credentialStatusBuilder_ == null) {
        credentialStatus_ = null;
      } else {
        credentialStatus_ = null;
        credentialStatusBuilder_ = null;
      }
      issuer_ = "";

      type_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      id_ = "";

      if (issuanceDateBuilder_ == null) {
        issuanceDate_ = null;
      } else {
        issuanceDate_ = null;
        issuanceDateBuilder_ = null;
      }
      if (expirationDateBuilder_ == null) {
        expirationDate_ = null;
      } else {
        expirationDate_ = null;
        expirationDateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return credential.v1.CredentialProto.internal_static_credential_v1_UnsignedCredential_descriptor;
    }

    @java.lang.Override
    public credential.v1.UnsignedCredential getDefaultInstanceForType() {
      return credential.v1.UnsignedCredential.getDefaultInstance();
    }

    @java.lang.Override
    public credential.v1.UnsignedCredential build() {
      credential.v1.UnsignedCredential result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public credential.v1.UnsignedCredential buildPartial() {
      credential.v1.UnsignedCredential result = new credential.v1.UnsignedCredential(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        context_ = context_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.context_ = context_;
      result.credentialSubject_ = credentialSubject_;
      if (credentialStatusBuilder_ == null) {
        result.credentialStatus_ = credentialStatus_;
      } else {
        result.credentialStatus_ = credentialStatusBuilder_.build();
      }
      result.issuer_ = issuer_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        type_ = type_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.type_ = type_;
      result.id_ = id_;
      if (issuanceDateBuilder_ == null) {
        result.issuanceDate_ = issuanceDate_;
      } else {
        result.issuanceDate_ = issuanceDateBuilder_.build();
      }
      if (expirationDateBuilder_ == null) {
        result.expirationDate_ = expirationDate_;
      } else {
        result.expirationDate_ = expirationDateBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof credential.v1.UnsignedCredential) {
        return mergeFrom((credential.v1.UnsignedCredential)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(credential.v1.UnsignedCredential other) {
      if (other == credential.v1.UnsignedCredential.getDefaultInstance()) return this;
      if (!other.context_.isEmpty()) {
        if (context_.isEmpty()) {
          context_ = other.context_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureContextIsMutable();
          context_.addAll(other.context_);
        }
        onChanged();
      }
      if (!other.getCredentialSubject().isEmpty()) {
        credentialSubject_ = other.credentialSubject_;
        onChanged();
      }
      if (other.hasCredentialStatus()) {
        mergeCredentialStatus(other.getCredentialStatus());
      }
      if (!other.getIssuer().isEmpty()) {
        issuer_ = other.issuer_;
        onChanged();
      }
      if (!other.type_.isEmpty()) {
        if (type_.isEmpty()) {
          type_ = other.type_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureTypeIsMutable();
          type_.addAll(other.type_);
        }
        onChanged();
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.hasIssuanceDate()) {
        mergeIssuanceDate(other.getIssuanceDate());
      }
      if (other.hasExpirationDate()) {
        mergeExpirationDate(other.getExpirationDate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      credential.v1.UnsignedCredential parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (credential.v1.UnsignedCredential) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList context_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureContextIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        context_ = new com.google.protobuf.LazyStringArrayList(context_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getContextList() {
      return context_.getUnmodifiableView();
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public int getContextCount() {
      return context_.size();
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public java.lang.String getContext(int index) {
      return context_.get(index);
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContextBytes(int index) {
      return context_.getByteString(index);
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public Builder setContext(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureContextIsMutable();
      context_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public Builder addContext(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureContextIsMutable();
      context_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public Builder addAllContext(
        java.lang.Iterable<java.lang.String> values) {
      ensureContextIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, context_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public Builder clearContext() {
      context_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string context = 1;</code>
     */
    public Builder addContextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureContextIsMutable();
      context_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object credentialSubject_ = "";
    /**
     * <code>string credential_subject = 2;</code>
     */
    public java.lang.String getCredentialSubject() {
      java.lang.Object ref = credentialSubject_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        credentialSubject_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string credential_subject = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCredentialSubjectBytes() {
      java.lang.Object ref = credentialSubject_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        credentialSubject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string credential_subject = 2;</code>
     */
    public Builder setCredentialSubject(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      credentialSubject_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string credential_subject = 2;</code>
     */
    public Builder clearCredentialSubject() {
      
      credentialSubject_ = getDefaultInstance().getCredentialSubject();
      onChanged();
      return this;
    }
    /**
     * <code>string credential_subject = 2;</code>
     */
    public Builder setCredentialSubjectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      credentialSubject_ = value;
      onChanged();
      return this;
    }

    private credential.v1.CredentialStatus credentialStatus_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        credential.v1.CredentialStatus, credential.v1.CredentialStatus.Builder, credential.v1.CredentialStatusOrBuilder> credentialStatusBuilder_;
    /**
     * <code>.credential.v1.CredentialStatus credential_status = 3;</code>
     */
    public boolean hasCredentialStatus() {
      return credentialStatusBuilder_ != null || credentialStatus_ != null;
    }
    /**
     * <code>.credential.v1.CredentialStatus credential_status = 3;</code>
     */
    public credential.v1.CredentialStatus getCredentialStatus() {
      if (credentialStatusBuilder_ == null) {
        return credentialStatus_ == null ? credential.v1.CredentialStatus.getDefaultInstance() : credentialStatus_;
      } else {
        return credentialStatusBuilder_.getMessage();
      }
    }
    /**
     * <code>.credential.v1.CredentialStatus credential_status = 3;</code>
     */
    public Builder setCredentialStatus(credential.v1.CredentialStatus value) {
      if (credentialStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        credentialStatus_ = value;
        onChanged();
      } else {
        credentialStatusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.credential.v1.CredentialStatus credential_status = 3;</code>
     */
    public Builder setCredentialStatus(
        credential.v1.CredentialStatus.Builder builderForValue) {
      if (credentialStatusBuilder_ == null) {
        credentialStatus_ = builderForValue.build();
        onChanged();
      } else {
        credentialStatusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.credential.v1.CredentialStatus credential_status = 3;</code>
     */
    public Builder mergeCredentialStatus(credential.v1.CredentialStatus value) {
      if (credentialStatusBuilder_ == null) {
        if (credentialStatus_ != null) {
          credentialStatus_ =
            credential.v1.CredentialStatus.newBuilder(credentialStatus_).mergeFrom(value).buildPartial();
        } else {
          credentialStatus_ = value;
        }
        onChanged();
      } else {
        credentialStatusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.credential.v1.CredentialStatus credential_status = 3;</code>
     */
    public Builder clearCredentialStatus() {
      if (credentialStatusBuilder_ == null) {
        credentialStatus_ = null;
        onChanged();
      } else {
        credentialStatus_ = null;
        credentialStatusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.credential.v1.CredentialStatus credential_status = 3;</code>
     */
    public credential.v1.CredentialStatus.Builder getCredentialStatusBuilder() {
      
      onChanged();
      return getCredentialStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.credential.v1.CredentialStatus credential_status = 3;</code>
     */
    public credential.v1.CredentialStatusOrBuilder getCredentialStatusOrBuilder() {
      if (credentialStatusBuilder_ != null) {
        return credentialStatusBuilder_.getMessageOrBuilder();
      } else {
        return credentialStatus_ == null ?
            credential.v1.CredentialStatus.getDefaultInstance() : credentialStatus_;
      }
    }
    /**
     * <code>.credential.v1.CredentialStatus credential_status = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        credential.v1.CredentialStatus, credential.v1.CredentialStatus.Builder, credential.v1.CredentialStatusOrBuilder> 
        getCredentialStatusFieldBuilder() {
      if (credentialStatusBuilder_ == null) {
        credentialStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            credential.v1.CredentialStatus, credential.v1.CredentialStatus.Builder, credential.v1.CredentialStatusOrBuilder>(
                getCredentialStatus(),
                getParentForChildren(),
                isClean());
        credentialStatus_ = null;
      }
      return credentialStatusBuilder_;
    }

    private java.lang.Object issuer_ = "";
    /**
     * <code>string issuer = 4;</code>
     */
    public java.lang.String getIssuer() {
      java.lang.Object ref = issuer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        issuer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string issuer = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIssuerBytes() {
      java.lang.Object ref = issuer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        issuer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string issuer = 4;</code>
     */
    public Builder setIssuer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      issuer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string issuer = 4;</code>
     */
    public Builder clearIssuer() {
      
      issuer_ = getDefaultInstance().getIssuer();
      onChanged();
      return this;
    }
    /**
     * <code>string issuer = 4;</code>
     */
    public Builder setIssuerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      issuer_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList type_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTypeIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        type_ = new com.google.protobuf.LazyStringArrayList(type_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated string type = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTypeList() {
      return type_.getUnmodifiableView();
    }
    /**
     * <code>repeated string type = 5;</code>
     */
    public int getTypeCount() {
      return type_.size();
    }
    /**
     * <code>repeated string type = 5;</code>
     */
    public java.lang.String getType(int index) {
      return type_.get(index);
    }
    /**
     * <code>repeated string type = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes(int index) {
      return type_.getByteString(index);
    }
    /**
     * <code>repeated string type = 5;</code>
     */
    public Builder setType(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTypeIsMutable();
      type_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type = 5;</code>
     */
    public Builder addType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTypeIsMutable();
      type_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type = 5;</code>
     */
    public Builder addAllType(
        java.lang.Iterable<java.lang.String> values) {
      ensureTypeIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, type_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type = 5;</code>
     */
    public Builder clearType() {
      type_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type = 5;</code>
     */
    public Builder addTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTypeIsMutable();
      type_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 6;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 6;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 6;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 6;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 6;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp issuanceDate_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> issuanceDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp issuance_date = 7;</code>
     */
    public boolean hasIssuanceDate() {
      return issuanceDateBuilder_ != null || issuanceDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp issuance_date = 7;</code>
     */
    public com.google.protobuf.Timestamp getIssuanceDate() {
      if (issuanceDateBuilder_ == null) {
        return issuanceDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : issuanceDate_;
      } else {
        return issuanceDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp issuance_date = 7;</code>
     */
    public Builder setIssuanceDate(com.google.protobuf.Timestamp value) {
      if (issuanceDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        issuanceDate_ = value;
        onChanged();
      } else {
        issuanceDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp issuance_date = 7;</code>
     */
    public Builder setIssuanceDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (issuanceDateBuilder_ == null) {
        issuanceDate_ = builderForValue.build();
        onChanged();
      } else {
        issuanceDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp issuance_date = 7;</code>
     */
    public Builder mergeIssuanceDate(com.google.protobuf.Timestamp value) {
      if (issuanceDateBuilder_ == null) {
        if (issuanceDate_ != null) {
          issuanceDate_ =
            com.google.protobuf.Timestamp.newBuilder(issuanceDate_).mergeFrom(value).buildPartial();
        } else {
          issuanceDate_ = value;
        }
        onChanged();
      } else {
        issuanceDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp issuance_date = 7;</code>
     */
    public Builder clearIssuanceDate() {
      if (issuanceDateBuilder_ == null) {
        issuanceDate_ = null;
        onChanged();
      } else {
        issuanceDate_ = null;
        issuanceDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp issuance_date = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getIssuanceDateBuilder() {
      
      onChanged();
      return getIssuanceDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp issuance_date = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getIssuanceDateOrBuilder() {
      if (issuanceDateBuilder_ != null) {
        return issuanceDateBuilder_.getMessageOrBuilder();
      } else {
        return issuanceDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : issuanceDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp issuance_date = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getIssuanceDateFieldBuilder() {
      if (issuanceDateBuilder_ == null) {
        issuanceDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getIssuanceDate(),
                getParentForChildren(),
                isClean());
        issuanceDate_ = null;
      }
      return issuanceDateBuilder_;
    }

    private com.google.protobuf.Timestamp expirationDate_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expirationDateBuilder_;
    /**
     * <pre>
     * optional in the ts types
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expiration_date = 16;</code>
     */
    public boolean hasExpirationDate() {
      return expirationDateBuilder_ != null || expirationDate_ != null;
    }
    /**
     * <pre>
     * optional in the ts types
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expiration_date = 16;</code>
     */
    public com.google.protobuf.Timestamp getExpirationDate() {
      if (expirationDateBuilder_ == null) {
        return expirationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expirationDate_;
      } else {
        return expirationDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * optional in the ts types
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expiration_date = 16;</code>
     */
    public Builder setExpirationDate(com.google.protobuf.Timestamp value) {
      if (expirationDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expirationDate_ = value;
        onChanged();
      } else {
        expirationDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * optional in the ts types
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expiration_date = 16;</code>
     */
    public Builder setExpirationDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expirationDateBuilder_ == null) {
        expirationDate_ = builderForValue.build();
        onChanged();
      } else {
        expirationDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * optional in the ts types
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expiration_date = 16;</code>
     */
    public Builder mergeExpirationDate(com.google.protobuf.Timestamp value) {
      if (expirationDateBuilder_ == null) {
        if (expirationDate_ != null) {
          expirationDate_ =
            com.google.protobuf.Timestamp.newBuilder(expirationDate_).mergeFrom(value).buildPartial();
        } else {
          expirationDate_ = value;
        }
        onChanged();
      } else {
        expirationDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * optional in the ts types
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expiration_date = 16;</code>
     */
    public Builder clearExpirationDate() {
      if (expirationDateBuilder_ == null) {
        expirationDate_ = null;
        onChanged();
      } else {
        expirationDate_ = null;
        expirationDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * optional in the ts types
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expiration_date = 16;</code>
     */
    public com.google.protobuf.Timestamp.Builder getExpirationDateBuilder() {
      
      onChanged();
      return getExpirationDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * optional in the ts types
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expiration_date = 16;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getExpirationDateOrBuilder() {
      if (expirationDateBuilder_ != null) {
        return expirationDateBuilder_.getMessageOrBuilder();
      } else {
        return expirationDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : expirationDate_;
      }
    }
    /**
     * <pre>
     * optional in the ts types
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expiration_date = 16;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getExpirationDateFieldBuilder() {
      if (expirationDateBuilder_ == null) {
        expirationDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getExpirationDate(),
                getParentForChildren(),
                isClean());
        expirationDate_ = null;
      }
      return expirationDateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:credential.v1.UnsignedCredential)
  }

  // @@protoc_insertion_point(class_scope:credential.v1.UnsignedCredential)
  private static final credential.v1.UnsignedCredential DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new credential.v1.UnsignedCredential();
  }

  public static credential.v1.UnsignedCredential getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UnsignedCredential>
      PARSER = new com.google.protobuf.AbstractParser<UnsignedCredential>() {
    @java.lang.Override
    public UnsignedCredential parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UnsignedCredential(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UnsignedCredential> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UnsignedCredential> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public credential.v1.UnsignedCredential getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

